// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum CameraOutcome {
  captured,
  cancelled,
  failed,
}

enum LocationOutcome {
  precise,
  approximate,
  permissionDenied,
  servicesDisabled,
  timeout,
  unavailable,
}

class CameraCaptureResult {
  CameraCaptureResult({
    required this.outcome,
    required this.outputPath,
    this.errorMessage,
  });

  CameraOutcome outcome;

  String outputPath;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      outcome,
      outputPath,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static CameraCaptureResult decode(Object result) {
    result as List<Object?>;
    return CameraCaptureResult(
      outcome: result[0]! as CameraOutcome,
      outputPath: result[1]! as String,
      errorMessage: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CameraCaptureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome) && _deepEquals(outputPath, other.outputPath) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'CameraCaptureResult(outcome: $outcome, outputPath: $outputPath, errorMessage: $errorMessage)';
  }
}

class RecoveredCameraCapture {
  RecoveredCameraCapture({
    required this.captureId,
    required this.outputPath,
    required this.hasContent,
  });

  String captureId;

  String outputPath;

  bool hasContent;

  List<Object?> _toList() {
    return <Object?>[
      captureId,
      outputPath,
      hasContent,
    ];
  }

  Object encode() {
    return _toList();  }

  static RecoveredCameraCapture decode(Object result) {
    result as List<Object?>;
    return RecoveredCameraCapture(
      captureId: result[0]! as String,
      outputPath: result[1]! as String,
      hasContent: result[2]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RecoveredCameraCapture || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(captureId, other.captureId) && _deepEquals(outputPath, other.outputPath) && _deepEquals(hasContent, other.hasContent);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RecoveredCameraCapture(captureId: $captureId, outputPath: $outputPath, hasContent: $hasContent)';
  }
}

class LocationResult {
  LocationResult({
    required this.outcome,
    this.latitude,
    this.longitude,
    this.accuracyMeters,
    this.address,
    this.errorMessage,
  });

  LocationOutcome outcome;

  double? latitude;

  double? longitude;

  double? accuracyMeters;

  String? address;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      outcome,
      latitude,
      longitude,
      accuracyMeters,
      address,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static LocationResult decode(Object result) {
    result as List<Object?>;
    return LocationResult(
      outcome: result[0]! as LocationOutcome,
      latitude: result[1] as double?,
      longitude: result[2] as double?,
      accuracyMeters: result[3] as double?,
      address: result[4] as String?,
      errorMessage: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LocationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(outcome, other.outcome) && _deepEquals(latitude, other.latitude) && _deepEquals(longitude, other.longitude) && _deepEquals(accuracyMeters, other.accuracyMeters) && _deepEquals(address, other.address) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LocationResult(outcome: $outcome, latitude: $latitude, longitude: $longitude, accuracyMeters: $accuracyMeters, address: $address, errorMessage: $errorMessage)';
  }
}

class MediaPublishResult {
  MediaPublishResult({
    required this.contentUri,
  });

  String contentUri;

  List<Object?> _toList() {
    return <Object?>[
      contentUri,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaPublishResult decode(Object result) {
    result as List<Object?>;
    return MediaPublishResult(
      contentUri: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaPublishResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(contentUri, other.contentUri);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaPublishResult(contentUri: $contentUri)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CameraOutcome) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is LocationOutcome) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is CameraCaptureResult) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is RecoveredCameraCapture) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is LocationResult) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is MediaPublishResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : CameraOutcome.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : LocationOutcome.values[value];
      case 131:
        return CameraCaptureResult.decode(readValue(buffer)!);
      case 132:
        return RecoveredCameraCapture.decode(readValue(buffer)!);
      case 133:
        return LocationResult.decode(readValue(buffer)!);
      case 134:
        return MediaPublishResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class SiteMarkSystemApi {
  /// Constructor for [SiteMarkSystemApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  SiteMarkSystemApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<String> createCameraTarget(String captureId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.createCameraTarget$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[captureId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<CameraCaptureResult> launchCamera(String captureId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.launchCamera$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[captureId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as CameraCaptureResult;
  }

  Future<RecoveredCameraCapture?> recoverCameraCapture() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.recoverCameraCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as RecoveredCameraCapture?;
  }

  Future<void> finishCameraCapture(String captureId, bool keepOriginal) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.finishCameraCapture$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[captureId, keepOriginal]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<LocationResult> requestCurrentLocation(int timeoutMillis) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.requestCurrentLocation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[timeoutMillis]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as LocationResult;
  }

  Future<MediaPublishResult> publishJpeg(String sourcePath, String displayName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.publishJpeg$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sourcePath, displayName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaPublishResult;
  }

  Future<void> deletePublishedImage(String contentUri) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.deletePublishedImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[contentUri]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}
