// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.12.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1164762658;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__image_core__export_project_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_project",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::image_core::ExportProjectRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::image_core::export_project(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_core__export_selection_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "export_selection",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::image_core::ExportSelectionRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::image_core::export_selection(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__simple__greet_impl(
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_sync::<flutter_rust_bridge::for_generated::SseCodec, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "greet",
            port: None,
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Sync,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_name = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            transform_result_sse::<_, ()>((move || {
                let output_ok = Result::<_, ()>::Ok(crate::api::simple::greet(api_name))?;
                Ok(output_ok)
            })())
        },
    )
}
fn wire__crate__api__simple__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::simple::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_core__render_photo_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "render_photo",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_request =
                <crate::api::image_core::RenderPhotoRequest>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::image_core::render_photo(api_request)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_core__sha256_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "sha256_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::image_core::sha256_file(api_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__image_core__verify_file_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verify_file",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_path = <String>::sse_decode(&mut deserializer);
            let api_expected_sha256 = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok =
                        crate::api::image_core::verify_file(api_path, api_expected_sha256)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::image_core::ExportPhotoRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_photoNumber = <String>::sse_decode(deserializer);
        let mut var_watermarkedPath = <String>::sse_decode(deserializer);
        let mut var_originalPath = <Option<String>>::sse_decode(deserializer);
        let mut var_originalSha256 = <String>::sse_decode(deserializer);
        let mut var_capturedAt = <String>::sse_decode(deserializer);
        let mut var_workLocation = <String>::sse_decode(deserializer);
        let mut var_workContent = <String>::sse_decode(deserializer);
        let mut var_photographer = <String>::sse_decode(deserializer);
        let mut var_address = <Option<String>>::sse_decode(deserializer);
        let mut var_coordinates = <Option<String>>::sse_decode(deserializer);
        let mut var_notes = <Option<String>>::sse_decode(deserializer);
        return crate::api::image_core::ExportPhotoRecord {
            photo_number: var_photoNumber,
            watermarked_path: var_watermarkedPath,
            original_path: var_originalPath,
            original_sha256: var_originalSha256,
            captured_at: var_capturedAt,
            work_location: var_workLocation,
            work_content: var_workContent,
            photographer: var_photographer,
            address: var_address,
            coordinates: var_coordinates,
            notes: var_notes,
        };
    }
}

impl SseDecode for crate::api::image_core::ExportProjectRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_projectId = <String>::sse_decode(deserializer);
        let mut var_projectName = <String>::sse_decode(deserializer);
        let mut var_outputZipPath = <String>::sse_decode(deserializer);
        let mut var_includeOriginals = <bool>::sse_decode(deserializer);
        let mut var_photos =
            <Vec<crate::api::image_core::ExportPhotoRecord>>::sse_decode(deserializer);
        return crate::api::image_core::ExportProjectRequest {
            project_id: var_projectId,
            project_name: var_projectName,
            output_zip_path: var_outputZipPath,
            include_originals: var_includeOriginals,
            photos: var_photos,
        };
    }
}

impl SseDecode for crate::api::image_core::ExportProjectResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputZipPath = <String>::sse_decode(deserializer);
        let mut var_archiveSha256 = <String>::sse_decode(deserializer);
        let mut var_photoCount = <u32>::sse_decode(deserializer);
        return crate::api::image_core::ExportProjectResult {
            output_zip_path: var_outputZipPath,
            archive_sha256: var_archiveSha256,
            photo_count: var_photoCount,
        };
    }
}

impl SseDecode for crate::api::image_core::ExportSelectionProject {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_projectId = <String>::sse_decode(deserializer);
        let mut var_projectName = <String>::sse_decode(deserializer);
        let mut var_photos =
            <Vec<crate::api::image_core::ExportPhotoRecord>>::sse_decode(deserializer);
        return crate::api::image_core::ExportSelectionProject {
            project_id: var_projectId,
            project_name: var_projectName,
            photos: var_photos,
        };
    }
}

impl SseDecode for crate::api::image_core::ExportSelectionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputZipPath = <String>::sse_decode(deserializer);
        let mut var_includeOriginals = <bool>::sse_decode(deserializer);
        let mut var_projects =
            <Vec<crate::api::image_core::ExportSelectionProject>>::sse_decode(deserializer);
        return crate::api::image_core::ExportSelectionRequest {
            output_zip_path: var_outputZipPath,
            include_originals: var_includeOriginals,
            projects: var_projects,
        };
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<crate::api::image_core::ExportPhotoRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::image_core::ExportPhotoRecord>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::image_core::ExportSelectionProject> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<crate::api::image_core::ExportSelectionProject>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for crate::api::image_core::RenderPhotoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sourcePath = <String>::sse_decode(deserializer);
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_projectName = <String>::sse_decode(deserializer);
        let mut var_workLocation = <String>::sse_decode(deserializer);
        let mut var_workContent = <String>::sse_decode(deserializer);
        let mut var_photographer = <String>::sse_decode(deserializer);
        let mut var_photoNumber = <String>::sse_decode(deserializer);
        let mut var_capturedAt = <String>::sse_decode(deserializer);
        let mut var_address = <Option<String>>::sse_decode(deserializer);
        let mut var_coordinates = <Option<String>>::sse_decode(deserializer);
        let mut var_notes = <Option<String>>::sse_decode(deserializer);
        let mut var_position =
            <crate::api::image_core::WatermarkPosition>::sse_decode(deserializer);
        let mut var_opacity = <f64>::sse_decode(deserializer);
        let mut var_accentColorArgb = <u32>::sse_decode(deserializer);
        let mut var_fontScale = <f64>::sse_decode(deserializer);
        let mut var_localeCode = <String>::sse_decode(deserializer);
        return crate::api::image_core::RenderPhotoRequest {
            source_path: var_sourcePath,
            output_path: var_outputPath,
            project_name: var_projectName,
            work_location: var_workLocation,
            work_content: var_workContent,
            photographer: var_photographer,
            photo_number: var_photoNumber,
            captured_at: var_capturedAt,
            address: var_address,
            coordinates: var_coordinates,
            notes: var_notes,
            position: var_position,
            opacity: var_opacity,
            accent_color_argb: var_accentColorArgb,
            font_scale: var_fontScale,
            locale_code: var_localeCode,
        };
    }
}

impl SseDecode for crate::api::image_core::RenderPhotoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_outputPath = <String>::sse_decode(deserializer);
        let mut var_outputSha256 = <String>::sse_decode(deserializer);
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        return crate::api::image_core::RenderPhotoResult {
            output_path: var_outputPath,
            output_sha256: var_outputSha256,
            width: var_width,
            height: var_height,
        };
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for crate::api::image_core::WatermarkPosition {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::image_core::WatermarkPosition::BottomLeft,
            1 => crate::api::image_core::WatermarkPosition::BottomRight,
            _ => unreachable!("Invalid variant for WatermarkPosition: {}", inner),
        };
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__crate__api__image_core__export_project_impl(port, ptr, rust_vec_len, data_len),
        2 => wire__crate__api__image_core__export_selection_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__crate__api__simple__init_app_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__crate__api__image_core__render_photo_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__image_core__sha256_file_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__crate__api__image_core__verify_file_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__api__simple__greet_impl(ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::ExportPhotoRecord {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.photo_number.into_into_dart().into_dart(),
            self.watermarked_path.into_into_dart().into_dart(),
            self.original_path.into_into_dart().into_dart(),
            self.original_sha256.into_into_dart().into_dart(),
            self.captured_at.into_into_dart().into_dart(),
            self.work_location.into_into_dart().into_dart(),
            self.work_content.into_into_dart().into_dart(),
            self.photographer.into_into_dart().into_dart(),
            self.address.into_into_dart().into_dart(),
            self.coordinates.into_into_dart().into_dart(),
            self.notes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::ExportPhotoRecord
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::ExportPhotoRecord>
    for crate::api::image_core::ExportPhotoRecord
{
    fn into_into_dart(self) -> crate::api::image_core::ExportPhotoRecord {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::ExportProjectRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.project_id.into_into_dart().into_dart(),
            self.project_name.into_into_dart().into_dart(),
            self.output_zip_path.into_into_dart().into_dart(),
            self.include_originals.into_into_dart().into_dart(),
            self.photos.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::ExportProjectRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::ExportProjectRequest>
    for crate::api::image_core::ExportProjectRequest
{
    fn into_into_dart(self) -> crate::api::image_core::ExportProjectRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::ExportProjectResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_zip_path.into_into_dart().into_dart(),
            self.archive_sha256.into_into_dart().into_dart(),
            self.photo_count.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::ExportProjectResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::ExportProjectResult>
    for crate::api::image_core::ExportProjectResult
{
    fn into_into_dart(self) -> crate::api::image_core::ExportProjectResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::ExportSelectionProject {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.project_id.into_into_dart().into_dart(),
            self.project_name.into_into_dart().into_dart(),
            self.photos.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::ExportSelectionProject
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::ExportSelectionProject>
    for crate::api::image_core::ExportSelectionProject
{
    fn into_into_dart(self) -> crate::api::image_core::ExportSelectionProject {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::ExportSelectionRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_zip_path.into_into_dart().into_dart(),
            self.include_originals.into_into_dart().into_dart(),
            self.projects.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::ExportSelectionRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::ExportSelectionRequest>
    for crate::api::image_core::ExportSelectionRequest
{
    fn into_into_dart(self) -> crate::api::image_core::ExportSelectionRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::RenderPhotoRequest {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.source_path.into_into_dart().into_dart(),
            self.output_path.into_into_dart().into_dart(),
            self.project_name.into_into_dart().into_dart(),
            self.work_location.into_into_dart().into_dart(),
            self.work_content.into_into_dart().into_dart(),
            self.photographer.into_into_dart().into_dart(),
            self.photo_number.into_into_dart().into_dart(),
            self.captured_at.into_into_dart().into_dart(),
            self.address.into_into_dart().into_dart(),
            self.coordinates.into_into_dart().into_dart(),
            self.notes.into_into_dart().into_dart(),
            self.position.into_into_dart().into_dart(),
            self.opacity.into_into_dart().into_dart(),
            self.accent_color_argb.into_into_dart().into_dart(),
            self.font_scale.into_into_dart().into_dart(),
            self.locale_code.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::RenderPhotoRequest
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::RenderPhotoRequest>
    for crate::api::image_core::RenderPhotoRequest
{
    fn into_into_dart(self) -> crate::api::image_core::RenderPhotoRequest {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::RenderPhotoResult {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.output_path.into_into_dart().into_dart(),
            self.output_sha256.into_into_dart().into_dart(),
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::RenderPhotoResult
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::RenderPhotoResult>
    for crate::api::image_core::RenderPhotoResult
{
    fn into_into_dart(self) -> crate::api::image_core::RenderPhotoResult {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::image_core::WatermarkPosition {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::BottomLeft => 0.into_dart(),
            Self::BottomRight => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::image_core::WatermarkPosition
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::image_core::WatermarkPosition>
    for crate::api::image_core::WatermarkPosition
{
    fn into_into_dart(self) -> crate::api::image_core::WatermarkPosition {
        self
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::image_core::ExportPhotoRecord {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.photo_number, serializer);
        <String>::sse_encode(self.watermarked_path, serializer);
        <Option<String>>::sse_encode(self.original_path, serializer);
        <String>::sse_encode(self.original_sha256, serializer);
        <String>::sse_encode(self.captured_at, serializer);
        <String>::sse_encode(self.work_location, serializer);
        <String>::sse_encode(self.work_content, serializer);
        <String>::sse_encode(self.photographer, serializer);
        <Option<String>>::sse_encode(self.address, serializer);
        <Option<String>>::sse_encode(self.coordinates, serializer);
        <Option<String>>::sse_encode(self.notes, serializer);
    }
}

impl SseEncode for crate::api::image_core::ExportProjectRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.project_id, serializer);
        <String>::sse_encode(self.project_name, serializer);
        <String>::sse_encode(self.output_zip_path, serializer);
        <bool>::sse_encode(self.include_originals, serializer);
        <Vec<crate::api::image_core::ExportPhotoRecord>>::sse_encode(self.photos, serializer);
    }
}

impl SseEncode for crate::api::image_core::ExportProjectResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_zip_path, serializer);
        <String>::sse_encode(self.archive_sha256, serializer);
        <u32>::sse_encode(self.photo_count, serializer);
    }
}

impl SseEncode for crate::api::image_core::ExportSelectionProject {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.project_id, serializer);
        <String>::sse_encode(self.project_name, serializer);
        <Vec<crate::api::image_core::ExportPhotoRecord>>::sse_encode(self.photos, serializer);
    }
}

impl SseEncode for crate::api::image_core::ExportSelectionRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_zip_path, serializer);
        <bool>::sse_encode(self.include_originals, serializer);
        <Vec<crate::api::image_core::ExportSelectionProject>>::sse_encode(
            self.projects,
            serializer,
        );
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<crate::api::image_core::ExportPhotoRecord> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::image_core::ExportPhotoRecord>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::image_core::ExportSelectionProject> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::image_core::ExportSelectionProject>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for crate::api::image_core::RenderPhotoRequest {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.source_path, serializer);
        <String>::sse_encode(self.output_path, serializer);
        <String>::sse_encode(self.project_name, serializer);
        <String>::sse_encode(self.work_location, serializer);
        <String>::sse_encode(self.work_content, serializer);
        <String>::sse_encode(self.photographer, serializer);
        <String>::sse_encode(self.photo_number, serializer);
        <String>::sse_encode(self.captured_at, serializer);
        <Option<String>>::sse_encode(self.address, serializer);
        <Option<String>>::sse_encode(self.coordinates, serializer);
        <Option<String>>::sse_encode(self.notes, serializer);
        <crate::api::image_core::WatermarkPosition>::sse_encode(self.position, serializer);
        <f64>::sse_encode(self.opacity, serializer);
        <u32>::sse_encode(self.accent_color_argb, serializer);
        <f64>::sse_encode(self.font_scale, serializer);
        <String>::sse_encode(self.locale_code, serializer);
    }
}

impl SseEncode for crate::api::image_core::RenderPhotoResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.output_path, serializer);
        <String>::sse_encode(self.output_sha256, serializer);
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for crate::api::image_core::WatermarkPosition {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::image_core::WatermarkPosition::BottomLeft => 0,
                crate::api::image_core::WatermarkPosition::BottomRight => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.12.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
