// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/image_core.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ExportProjectRequest dco_decode_box_autoadd_export_project_request(
    dynamic raw,
  );

  @protected
  RenderPhotoRequest dco_decode_box_autoadd_render_photo_request(dynamic raw);

  @protected
  ExportPhotoRecord dco_decode_export_photo_record(dynamic raw);

  @protected
  ExportProjectRequest dco_decode_export_project_request(dynamic raw);

  @protected
  ExportProjectResult dco_decode_export_project_result(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ExportPhotoRecord> dco_decode_list_export_photo_record(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RenderPhotoRequest dco_decode_render_photo_request(dynamic raw);

  @protected
  RenderPhotoResult dco_decode_render_photo_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WatermarkPosition dco_decode_watermark_position(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ExportProjectRequest sse_decode_box_autoadd_export_project_request(
    SseDeserializer deserializer,
  );

  @protected
  RenderPhotoRequest sse_decode_box_autoadd_render_photo_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportPhotoRecord sse_decode_export_photo_record(
    SseDeserializer deserializer,
  );

  @protected
  ExportProjectRequest sse_decode_export_project_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportProjectResult sse_decode_export_project_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ExportPhotoRecord> sse_decode_list_export_photo_record(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RenderPhotoRequest sse_decode_render_photo_request(
    SseDeserializer deserializer,
  );

  @protected
  RenderPhotoResult sse_decode_render_photo_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WatermarkPosition sse_decode_watermark_position(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_photo_record(
    ExportPhotoRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_project_result(
    ExportProjectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_export_photo_record(
    List<ExportPhotoRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_render_photo_result(
    RenderPhotoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_watermark_position(
    WatermarkPosition self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
