// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/image_core.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -70732977;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'sitemark_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ExportProjectResult> crateApiImageCoreExportProject({
    required ExportProjectRequest request,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<RenderPhotoResult> crateApiImageCoreRenderPhoto({
    required RenderPhotoRequest request,
  });

  Future<String> crateApiImageCoreSha256File({required String path});

  Future<bool> crateApiImageCoreVerifyFile({
    required String path,
    required String expectedSha256,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ExportProjectResult> crateApiImageCoreExportProject({
    required ExportProjectRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_export_project_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_export_project_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreExportProjectConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreExportProjectConstMeta =>
      const TaskConstMeta(debugName: "export_project", argNames: ["request"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<RenderPhotoResult> crateApiImageCoreRenderPhoto({
    required RenderPhotoRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_render_photo_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_photo_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreRenderPhotoConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreRenderPhotoConstMeta =>
      const TaskConstMeta(debugName: "render_photo", argNames: ["request"]);

  @override
  Future<String> crateApiImageCoreSha256File({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreSha256FileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreSha256FileConstMeta =>
      const TaskConstMeta(debugName: "sha256_file", argNames: ["path"]);

  @override
  Future<bool> crateApiImageCoreVerifyFile({
    required String path,
    required String expectedSha256,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(expectedSha256, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreVerifyFileConstMeta,
        argValues: [path, expectedSha256],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreVerifyFileConstMeta =>
      const TaskConstMeta(
        debugName: "verify_file",
        argNames: ["path", "expectedSha256"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ExportProjectRequest dco_decode_box_autoadd_export_project_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_export_project_request(raw);
  }

  @protected
  RenderPhotoRequest dco_decode_box_autoadd_render_photo_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_render_photo_request(raw);
  }

  @protected
  ExportPhotoRecord dco_decode_export_photo_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 11)
      throw Exception('unexpected arr length: expect 11 but see ${arr.length}');
    return ExportPhotoRecord(
      photoNumber: dco_decode_String(arr[0]),
      watermarkedPath: dco_decode_String(arr[1]),
      originalPath: dco_decode_opt_String(arr[2]),
      originalSha256: dco_decode_String(arr[3]),
      capturedAt: dco_decode_String(arr[4]),
      workLocation: dco_decode_String(arr[5]),
      workContent: dco_decode_String(arr[6]),
      photographer: dco_decode_String(arr[7]),
      address: dco_decode_opt_String(arr[8]),
      coordinates: dco_decode_opt_String(arr[9]),
      notes: dco_decode_opt_String(arr[10]),
    );
  }

  @protected
  ExportProjectRequest dco_decode_export_project_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ExportProjectRequest(
      projectId: dco_decode_String(arr[0]),
      projectName: dco_decode_String(arr[1]),
      outputZipPath: dco_decode_String(arr[2]),
      includeOriginals: dco_decode_bool(arr[3]),
      photos: dco_decode_list_export_photo_record(arr[4]),
    );
  }

  @protected
  ExportProjectResult dco_decode_export_project_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExportProjectResult(
      outputZipPath: dco_decode_String(arr[0]),
      archiveSha256: dco_decode_String(arr[1]),
      photoCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ExportPhotoRecord> dco_decode_list_export_photo_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_export_photo_record).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RenderPhotoRequest dco_decode_render_photo_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return RenderPhotoRequest(
      sourcePath: dco_decode_String(arr[0]),
      outputPath: dco_decode_String(arr[1]),
      projectName: dco_decode_String(arr[2]),
      workLocation: dco_decode_String(arr[3]),
      workContent: dco_decode_String(arr[4]),
      photographer: dco_decode_String(arr[5]),
      photoNumber: dco_decode_String(arr[6]),
      capturedAt: dco_decode_String(arr[7]),
      address: dco_decode_opt_String(arr[8]),
      coordinates: dco_decode_opt_String(arr[9]),
      notes: dco_decode_opt_String(arr[10]),
      position: dco_decode_watermark_position(arr[11]),
      opacity: dco_decode_f_64(arr[12]),
      accentColorArgb: dco_decode_u_32(arr[13]),
      fontScale: dco_decode_f_64(arr[14]),
      localeCode: dco_decode_String(arr[15]),
    );
  }

  @protected
  RenderPhotoResult dco_decode_render_photo_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RenderPhotoResult(
      outputPath: dco_decode_String(arr[0]),
      outputSha256: dco_decode_String(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WatermarkPosition dco_decode_watermark_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WatermarkPosition.values[raw as int];
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ExportProjectRequest sse_decode_box_autoadd_export_project_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_export_project_request(deserializer));
  }

  @protected
  RenderPhotoRequest sse_decode_box_autoadd_render_photo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_render_photo_request(deserializer));
  }

  @protected
  ExportPhotoRecord sse_decode_export_photo_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_photoNumber = sse_decode_String(deserializer);
    var var_watermarkedPath = sse_decode_String(deserializer);
    var var_originalPath = sse_decode_opt_String(deserializer);
    var var_originalSha256 = sse_decode_String(deserializer);
    var var_capturedAt = sse_decode_String(deserializer);
    var var_workLocation = sse_decode_String(deserializer);
    var var_workContent = sse_decode_String(deserializer);
    var var_photographer = sse_decode_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_coordinates = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return ExportPhotoRecord(
      photoNumber: var_photoNumber,
      watermarkedPath: var_watermarkedPath,
      originalPath: var_originalPath,
      originalSha256: var_originalSha256,
      capturedAt: var_capturedAt,
      workLocation: var_workLocation,
      workContent: var_workContent,
      photographer: var_photographer,
      address: var_address,
      coordinates: var_coordinates,
      notes: var_notes,
    );
  }

  @protected
  ExportProjectRequest sse_decode_export_project_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectId = sse_decode_String(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_outputZipPath = sse_decode_String(deserializer);
    var var_includeOriginals = sse_decode_bool(deserializer);
    var var_photos = sse_decode_list_export_photo_record(deserializer);
    return ExportProjectRequest(
      projectId: var_projectId,
      projectName: var_projectName,
      outputZipPath: var_outputZipPath,
      includeOriginals: var_includeOriginals,
      photos: var_photos,
    );
  }

  @protected
  ExportProjectResult sse_decode_export_project_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputZipPath = sse_decode_String(deserializer);
    var var_archiveSha256 = sse_decode_String(deserializer);
    var var_photoCount = sse_decode_u_32(deserializer);
    return ExportProjectResult(
      outputZipPath: var_outputZipPath,
      archiveSha256: var_archiveSha256,
      photoCount: var_photoCount,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ExportPhotoRecord> sse_decode_list_export_photo_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExportPhotoRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_export_photo_record(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RenderPhotoRequest sse_decode_render_photo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_workLocation = sse_decode_String(deserializer);
    var var_workContent = sse_decode_String(deserializer);
    var var_photographer = sse_decode_String(deserializer);
    var var_photoNumber = sse_decode_String(deserializer);
    var var_capturedAt = sse_decode_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_coordinates = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_position = sse_decode_watermark_position(deserializer);
    var var_opacity = sse_decode_f_64(deserializer);
    var var_accentColorArgb = sse_decode_u_32(deserializer);
    var var_fontScale = sse_decode_f_64(deserializer);
    var var_localeCode = sse_decode_String(deserializer);
    return RenderPhotoRequest(
      sourcePath: var_sourcePath,
      outputPath: var_outputPath,
      projectName: var_projectName,
      workLocation: var_workLocation,
      workContent: var_workContent,
      photographer: var_photographer,
      photoNumber: var_photoNumber,
      capturedAt: var_capturedAt,
      address: var_address,
      coordinates: var_coordinates,
      notes: var_notes,
      position: var_position,
      opacity: var_opacity,
      accentColorArgb: var_accentColorArgb,
      fontScale: var_fontScale,
      localeCode: var_localeCode,
    );
  }

  @protected
  RenderPhotoResult sse_decode_render_photo_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputPath = sse_decode_String(deserializer);
    var var_outputSha256 = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return RenderPhotoResult(
      outputPath: var_outputPath,
      outputSha256: var_outputSha256,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WatermarkPosition sse_decode_watermark_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WatermarkPosition.values[inner];
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_project_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_render_photo_request(self, serializer);
  }

  @protected
  void sse_encode_export_photo_record(
    ExportPhotoRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.photoNumber, serializer);
    sse_encode_String(self.watermarkedPath, serializer);
    sse_encode_opt_String(self.originalPath, serializer);
    sse_encode_String(self.originalSha256, serializer);
    sse_encode_String(self.capturedAt, serializer);
    sse_encode_String(self.workLocation, serializer);
    sse_encode_String(self.workContent, serializer);
    sse_encode_String(self.photographer, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.coordinates, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectId, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_String(self.outputZipPath, serializer);
    sse_encode_bool(self.includeOriginals, serializer);
    sse_encode_list_export_photo_record(self.photos, serializer);
  }

  @protected
  void sse_encode_export_project_result(
    ExportProjectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputZipPath, serializer);
    sse_encode_String(self.archiveSha256, serializer);
    sse_encode_u_32(self.photoCount, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_export_photo_record(
    List<ExportPhotoRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_export_photo_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.outputPath, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_String(self.workLocation, serializer);
    sse_encode_String(self.workContent, serializer);
    sse_encode_String(self.photographer, serializer);
    sse_encode_String(self.photoNumber, serializer);
    sse_encode_String(self.capturedAt, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.coordinates, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_watermark_position(self.position, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_u_32(self.accentColorArgb, serializer);
    sse_encode_f_64(self.fontScale, serializer);
    sse_encode_String(self.localeCode, serializer);
  }

  @protected
  void sse_encode_render_photo_result(
    RenderPhotoResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputPath, serializer);
    sse_encode_String(self.outputSha256, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_watermark_position(
    WatermarkPosition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
