// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/image_core.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1907292496;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'sitemark_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ExportProjectResult> crateApiImageCoreExportProject({
    required ExportProjectRequest request,
  });

  Future<ExportProjectResult> crateApiImageCoreExportProjectBundle({
    required ExportProjectBundleRequest request,
  });

  Future<ExportProjectResult> crateApiImageCoreExportSelection({
    required ExportSelectionRequest request,
  });

  Future<ExtractedArchivePhoto> crateApiImageCoreExtractArchivePhoto({
    required ExtractArchivePhotoRequest request,
  });

  Future<void> crateApiImageCoreExtractProjectBundleEntry({
    required ExtractProjectBundleEntryRequest request,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<ProjectArchivePreview> crateApiImageCoreReadProjectArchive({
    required String zipPath,
  });

  Future<ProjectBundlePreview> crateApiImageCoreReadProjectBundle({
    required String zipPath,
  });

  Future<RenderPhotoResult> crateApiImageCoreRenderPhoto({
    required RenderPhotoRequest request,
  });

  Future<String> crateApiImageCoreSha256File({required String path});

  Future<bool> crateApiImageCoreVerifyFile({
    required String path,
    required String expectedSha256,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ExportProjectResult> crateApiImageCoreExportProject({
    required ExportProjectRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_export_project_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_export_project_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreExportProjectConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreExportProjectConstMeta =>
      const TaskConstMeta(debugName: "export_project", argNames: ["request"]);

  @override
  Future<ExportProjectResult> crateApiImageCoreExportProjectBundle({
    required ExportProjectBundleRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_export_project_bundle_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_export_project_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreExportProjectBundleConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreExportProjectBundleConstMeta =>
      const TaskConstMeta(
        debugName: "export_project_bundle",
        argNames: ["request"],
      );

  @override
  Future<ExportProjectResult> crateApiImageCoreExportSelection({
    required ExportSelectionRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_export_selection_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_export_project_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreExportSelectionConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreExportSelectionConstMeta =>
      const TaskConstMeta(debugName: "export_selection", argNames: ["request"]);

  @override
  Future<ExtractedArchivePhoto> crateApiImageCoreExtractArchivePhoto({
    required ExtractArchivePhotoRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_extract_archive_photo_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_extracted_archive_photo,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreExtractArchivePhotoConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreExtractArchivePhotoConstMeta =>
      const TaskConstMeta(
        debugName: "extract_archive_photo",
        argNames: ["request"],
      );

  @override
  Future<void> crateApiImageCoreExtractProjectBundleEntry({
    required ExtractProjectBundleEntryRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_extract_project_bundle_entry_request(
            request,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreExtractProjectBundleEntryConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreExtractProjectBundleEntryConstMeta =>
      const TaskConstMeta(
        debugName: "extract_project_bundle_entry",
        argNames: ["request"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<ProjectArchivePreview> crateApiImageCoreReadProjectArchive({
    required String zipPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(zipPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_archive_preview,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreReadProjectArchiveConstMeta,
        argValues: [zipPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreReadProjectArchiveConstMeta =>
      const TaskConstMeta(
        debugName: "read_project_archive",
        argNames: ["zipPath"],
      );

  @override
  Future<ProjectBundlePreview> crateApiImageCoreReadProjectBundle({
    required String zipPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(zipPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_bundle_preview,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreReadProjectBundleConstMeta,
        argValues: [zipPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreReadProjectBundleConstMeta =>
      const TaskConstMeta(
        debugName: "read_project_bundle",
        argNames: ["zipPath"],
      );

  @override
  Future<RenderPhotoResult> crateApiImageCoreRenderPhoto({
    required RenderPhotoRequest request,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_render_photo_request(request, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_render_photo_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreRenderPhotoConstMeta,
        argValues: [request],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreRenderPhotoConstMeta =>
      const TaskConstMeta(debugName: "render_photo", argNames: ["request"]);

  @override
  Future<String> crateApiImageCoreSha256File({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreSha256FileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreSha256FileConstMeta =>
      const TaskConstMeta(debugName: "sha256_file", argNames: ["path"]);

  @override
  Future<bool> crateApiImageCoreVerifyFile({
    required String path,
    required String expectedSha256,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(expectedSha256, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiImageCoreVerifyFileConstMeta,
        argValues: [path, expectedSha256],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImageCoreVerifyFileConstMeta =>
      const TaskConstMeta(
        debugName: "verify_file",
        argNames: ["path", "expectedSha256"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ArchiveCaptureTemplate dco_decode_archive_capture_template(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ArchiveCaptureTemplate(
      name: dco_decode_String(arr[0]),
      workLocation: dco_decode_String(arr[1]),
      workContent: dco_decode_String(arr[2]),
      photographer: dco_decode_String(arr[3]),
      createdAt: dco_decode_String(arr[4]),
      updatedAt: dco_decode_String(arr[5]),
    );
  }

  @protected
  ArchivePhotoPreview dco_decode_archive_photo_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 13)
      throw Exception('unexpected arr length: expect 13 but see ${arr.length}');
    return ArchivePhotoPreview(
      photoNumber: dco_decode_String(arr[0]),
      hasOriginal: dco_decode_bool(arr[1]),
      originalSha256: dco_decode_String(arr[2]),
      capturedAt: dco_decode_String(arr[3]),
      workLocation: dco_decode_String(arr[4]),
      workContent: dco_decode_String(arr[5]),
      photographer: dco_decode_String(arr[6]),
      address: dco_decode_opt_String(arr[7]),
      notes: dco_decode_opt_String(arr[8]),
      latitude: dco_decode_opt_box_autoadd_f_64(arr[9]),
      longitude: dco_decode_opt_box_autoadd_f_64(arr[10]),
      accuracyMeters: dco_decode_opt_box_autoadd_f_64(arr[11]),
      watermarkLocaleCode: dco_decode_opt_String(arr[12]),
    );
  }

  @protected
  ArchiveWatermarkSettings dco_decode_archive_watermark_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ArchiveWatermarkSettings(
      position: dco_decode_String(arr[0]),
      opacity: dco_decode_f_64(arr[1]),
      accentColorArgb: dco_decode_u_32(arr[2]),
      fontScale: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ArchiveWatermarkSettings dco_decode_box_autoadd_archive_watermark_settings(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_archive_watermark_settings(raw);
  }

  @protected
  ExportProjectBundleRequest
  dco_decode_box_autoadd_export_project_bundle_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_export_project_bundle_request(raw);
  }

  @protected
  ExportProjectRequest dco_decode_box_autoadd_export_project_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_export_project_request(raw);
  }

  @protected
  ExportSelectionRequest dco_decode_box_autoadd_export_selection_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_export_selection_request(raw);
  }

  @protected
  ExtractArchivePhotoRequest
  dco_decode_box_autoadd_extract_archive_photo_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_extract_archive_photo_request(raw);
  }

  @protected
  ExtractProjectBundleEntryRequest
  dco_decode_box_autoadd_extract_project_bundle_entry_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_extract_project_bundle_entry_request(raw);
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  RenderPhotoRequest dco_decode_box_autoadd_render_photo_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_render_photo_request(raw);
  }

  @protected
  ExportCaptureTemplate dco_decode_export_capture_template(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ExportCaptureTemplate(
      name: dco_decode_String(arr[0]),
      workLocation: dco_decode_String(arr[1]),
      workContent: dco_decode_String(arr[2]),
      photographer: dco_decode_String(arr[3]),
      createdAt: dco_decode_String(arr[4]),
      updatedAt: dco_decode_String(arr[5]),
    );
  }

  @protected
  ExportPhotoRecord dco_decode_export_photo_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 15)
      throw Exception('unexpected arr length: expect 15 but see ${arr.length}');
    return ExportPhotoRecord(
      photoNumber: dco_decode_String(arr[0]),
      watermarkedPath: dco_decode_String(arr[1]),
      originalPath: dco_decode_opt_String(arr[2]),
      originalSha256: dco_decode_String(arr[3]),
      capturedAt: dco_decode_String(arr[4]),
      workLocation: dco_decode_String(arr[5]),
      workContent: dco_decode_String(arr[6]),
      photographer: dco_decode_String(arr[7]),
      address: dco_decode_opt_String(arr[8]),
      coordinates: dco_decode_opt_String(arr[9]),
      notes: dco_decode_opt_String(arr[10]),
      latitude: dco_decode_opt_box_autoadd_f_64(arr[11]),
      longitude: dco_decode_opt_box_autoadd_f_64(arr[12]),
      accuracyMeters: dco_decode_opt_box_autoadd_f_64(arr[13]),
      watermarkLocaleCode: dco_decode_opt_String(arr[14]),
    );
  }

  @protected
  ExportProjectBundleRequest dco_decode_export_project_bundle_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExportProjectBundleRequest(
      outputZipPath: dco_decode_String(arr[0]),
      projects: dco_decode_list_project_bundle_source(arr[1]),
    );
  }

  @protected
  ExportProjectRequest dco_decode_export_project_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return ExportProjectRequest(
      projectId: dco_decode_String(arr[0]),
      projectName: dco_decode_String(arr[1]),
      projectDescription: dco_decode_opt_String(arr[2]),
      projectCreatedAt: dco_decode_String(arr[3]),
      snapshotAt: dco_decode_String(arr[4]),
      omittedProcessingCount: dco_decode_u_32(arr[5]),
      omittedFailedCount: dco_decode_u_32(arr[6]),
      outputZipPath: dco_decode_String(arr[7]),
      includeOriginals: dco_decode_bool(arr[8]),
      watermark: dco_decode_export_watermark_settings(arr[9]),
      photos: dco_decode_list_export_photo_record(arr[10]),
      templates: dco_decode_list_export_capture_template(arr[11]),
    );
  }

  @protected
  ExportProjectResult dco_decode_export_project_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExportProjectResult(
      outputZipPath: dco_decode_String(arr[0]),
      archiveSha256: dco_decode_String(arr[1]),
      photoCount: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ExportSelectionProject dco_decode_export_selection_project(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExportSelectionProject(
      projectId: dco_decode_String(arr[0]),
      projectName: dco_decode_String(arr[1]),
      photos: dco_decode_list_export_photo_record(arr[2]),
    );
  }

  @protected
  ExportSelectionRequest dco_decode_export_selection_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExportSelectionRequest(
      outputZipPath: dco_decode_String(arr[0]),
      includeOriginals: dco_decode_bool(arr[1]),
      projects: dco_decode_list_export_selection_project(arr[2]),
    );
  }

  @protected
  ExportWatermarkSettings dco_decode_export_watermark_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ExportWatermarkSettings(
      position: dco_decode_String(arr[0]),
      opacity: dco_decode_f_64(arr[1]),
      accentColorArgb: dco_decode_u_32(arr[2]),
      fontScale: dco_decode_f_64(arr[3]),
    );
  }

  @protected
  ExtractArchivePhotoRequest dco_decode_extract_archive_photo_request(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ExtractArchivePhotoRequest(
      zipPath: dco_decode_String(arr[0]),
      photoNumber: dco_decode_String(arr[1]),
      renderedDestination: dco_decode_String(arr[2]),
      originalDestination: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  ExtractProjectBundleEntryRequest
  dco_decode_extract_project_bundle_entry_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ExtractProjectBundleEntryRequest(
      zipPath: dco_decode_String(arr[0]),
      archivePath: dco_decode_String(arr[1]),
      outputPath: dco_decode_String(arr[2]),
    );
  }

  @protected
  ExtractedArchivePhoto dco_decode_extracted_archive_photo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ExtractedArchivePhoto(
      renderedPath: dco_decode_String(arr[0]),
      originalPath: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<ArchiveCaptureTemplate> dco_decode_list_archive_capture_template(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_archive_capture_template)
        .toList();
  }

  @protected
  List<ArchivePhotoPreview> dco_decode_list_archive_photo_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_archive_photo_preview)
        .toList();
  }

  @protected
  List<ExportCaptureTemplate> dco_decode_list_export_capture_template(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_export_capture_template)
        .toList();
  }

  @protected
  List<ExportPhotoRecord> dco_decode_list_export_photo_record(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_export_photo_record).toList();
  }

  @protected
  List<ExportSelectionProject> dco_decode_list_export_selection_project(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_export_selection_project)
        .toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProjectBundleEntryPreview> dco_decode_list_project_bundle_entry_preview(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_project_bundle_entry_preview)
        .toList();
  }

  @protected
  List<ProjectBundleSource> dco_decode_list_project_bundle_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_project_bundle_source)
        .toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ArchiveWatermarkSettings?
  dco_decode_opt_box_autoadd_archive_watermark_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_archive_watermark_settings(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  ProjectArchivePreview dco_decode_project_archive_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return ProjectArchivePreview(
      schemaVersion: dco_decode_u_32(arr[0]),
      projectName: dco_decode_String(arr[1]),
      projectDescription: dco_decode_opt_String(arr[2]),
      projectCreatedAt: dco_decode_opt_String(arr[3]),
      snapshotAt: dco_decode_opt_String(arr[4]),
      omittedProcessingCount: dco_decode_u_32(arr[5]),
      omittedFailedCount: dco_decode_u_32(arr[6]),
      isPartial: dco_decode_bool(arr[7]),
      includesOriginals: dco_decode_bool(arr[8]),
      watermark: dco_decode_opt_box_autoadd_archive_watermark_settings(arr[9]),
      photos: dco_decode_list_archive_photo_preview(arr[10]),
      templates: dco_decode_list_archive_capture_template(arr[11]),
    );
  }

  @protected
  ProjectBundleEntryPreview dco_decode_project_bundle_entry_preview(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProjectBundleEntryPreview(
      projectId: dco_decode_String(arr[0]),
      projectName: dco_decode_String(arr[1]),
      archivePath: dco_decode_String(arr[2]),
      archiveSha256: dco_decode_String(arr[3]),
    );
  }

  @protected
  ProjectBundlePreview dco_decode_project_bundle_preview(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProjectBundlePreview(
      schemaVersion: dco_decode_u_32(arr[0]),
      createdAt: dco_decode_String(arr[1]),
      projects: dco_decode_list_project_bundle_entry_preview(arr[2]),
    );
  }

  @protected
  ProjectBundleSource dco_decode_project_bundle_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ProjectBundleSource(
      projectId: dco_decode_String(arr[0]),
      projectName: dco_decode_String(arr[1]),
      archivePath: dco_decode_String(arr[2]),
    );
  }

  @protected
  RenderPhotoRequest dco_decode_render_photo_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 16)
      throw Exception('unexpected arr length: expect 16 but see ${arr.length}');
    return RenderPhotoRequest(
      sourcePath: dco_decode_String(arr[0]),
      outputPath: dco_decode_String(arr[1]),
      projectName: dco_decode_String(arr[2]),
      workLocation: dco_decode_String(arr[3]),
      workContent: dco_decode_String(arr[4]),
      photographer: dco_decode_String(arr[5]),
      photoNumber: dco_decode_String(arr[6]),
      capturedAt: dco_decode_String(arr[7]),
      address: dco_decode_opt_String(arr[8]),
      coordinates: dco_decode_opt_String(arr[9]),
      notes: dco_decode_opt_String(arr[10]),
      position: dco_decode_watermark_position(arr[11]),
      opacity: dco_decode_f_64(arr[12]),
      accentColorArgb: dco_decode_u_32(arr[13]),
      fontScale: dco_decode_f_64(arr[14]),
      localeCode: dco_decode_String(arr[15]),
    );
  }

  @protected
  RenderPhotoResult dco_decode_render_photo_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RenderPhotoResult(
      outputPath: dco_decode_String(arr[0]),
      outputSha256: dco_decode_String(arr[1]),
      width: dco_decode_u_32(arr[2]),
      height: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WatermarkPosition dco_decode_watermark_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return WatermarkPosition.values[raw as int];
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ArchiveCaptureTemplate sse_decode_archive_capture_template(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_workLocation = sse_decode_String(deserializer);
    var var_workContent = sse_decode_String(deserializer);
    var var_photographer = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return ArchiveCaptureTemplate(
      name: var_name,
      workLocation: var_workLocation,
      workContent: var_workContent,
      photographer: var_photographer,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  ArchivePhotoPreview sse_decode_archive_photo_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_photoNumber = sse_decode_String(deserializer);
    var var_hasOriginal = sse_decode_bool(deserializer);
    var var_originalSha256 = sse_decode_String(deserializer);
    var var_capturedAt = sse_decode_String(deserializer);
    var var_workLocation = sse_decode_String(deserializer);
    var var_workContent = sse_decode_String(deserializer);
    var var_photographer = sse_decode_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_latitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_longitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_accuracyMeters = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_watermarkLocaleCode = sse_decode_opt_String(deserializer);
    return ArchivePhotoPreview(
      photoNumber: var_photoNumber,
      hasOriginal: var_hasOriginal,
      originalSha256: var_originalSha256,
      capturedAt: var_capturedAt,
      workLocation: var_workLocation,
      workContent: var_workContent,
      photographer: var_photographer,
      address: var_address,
      notes: var_notes,
      latitude: var_latitude,
      longitude: var_longitude,
      accuracyMeters: var_accuracyMeters,
      watermarkLocaleCode: var_watermarkLocaleCode,
    );
  }

  @protected
  ArchiveWatermarkSettings sse_decode_archive_watermark_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_position = sse_decode_String(deserializer);
    var var_opacity = sse_decode_f_64(deserializer);
    var var_accentColorArgb = sse_decode_u_32(deserializer);
    var var_fontScale = sse_decode_f_64(deserializer);
    return ArchiveWatermarkSettings(
      position: var_position,
      opacity: var_opacity,
      accentColorArgb: var_accentColorArgb,
      fontScale: var_fontScale,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ArchiveWatermarkSettings sse_decode_box_autoadd_archive_watermark_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_archive_watermark_settings(deserializer));
  }

  @protected
  ExportProjectBundleRequest
  sse_decode_box_autoadd_export_project_bundle_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_export_project_bundle_request(deserializer));
  }

  @protected
  ExportProjectRequest sse_decode_box_autoadd_export_project_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_export_project_request(deserializer));
  }

  @protected
  ExportSelectionRequest sse_decode_box_autoadd_export_selection_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_export_selection_request(deserializer));
  }

  @protected
  ExtractArchivePhotoRequest
  sse_decode_box_autoadd_extract_archive_photo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_extract_archive_photo_request(deserializer));
  }

  @protected
  ExtractProjectBundleEntryRequest
  sse_decode_box_autoadd_extract_project_bundle_entry_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_extract_project_bundle_entry_request(deserializer));
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  RenderPhotoRequest sse_decode_box_autoadd_render_photo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_render_photo_request(deserializer));
  }

  @protected
  ExportCaptureTemplate sse_decode_export_capture_template(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_workLocation = sse_decode_String(deserializer);
    var var_workContent = sse_decode_String(deserializer);
    var var_photographer = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_updatedAt = sse_decode_String(deserializer);
    return ExportCaptureTemplate(
      name: var_name,
      workLocation: var_workLocation,
      workContent: var_workContent,
      photographer: var_photographer,
      createdAt: var_createdAt,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  ExportPhotoRecord sse_decode_export_photo_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_photoNumber = sse_decode_String(deserializer);
    var var_watermarkedPath = sse_decode_String(deserializer);
    var var_originalPath = sse_decode_opt_String(deserializer);
    var var_originalSha256 = sse_decode_String(deserializer);
    var var_capturedAt = sse_decode_String(deserializer);
    var var_workLocation = sse_decode_String(deserializer);
    var var_workContent = sse_decode_String(deserializer);
    var var_photographer = sse_decode_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_coordinates = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_latitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_longitude = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_accuracyMeters = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_watermarkLocaleCode = sse_decode_opt_String(deserializer);
    return ExportPhotoRecord(
      photoNumber: var_photoNumber,
      watermarkedPath: var_watermarkedPath,
      originalPath: var_originalPath,
      originalSha256: var_originalSha256,
      capturedAt: var_capturedAt,
      workLocation: var_workLocation,
      workContent: var_workContent,
      photographer: var_photographer,
      address: var_address,
      coordinates: var_coordinates,
      notes: var_notes,
      latitude: var_latitude,
      longitude: var_longitude,
      accuracyMeters: var_accuracyMeters,
      watermarkLocaleCode: var_watermarkLocaleCode,
    );
  }

  @protected
  ExportProjectBundleRequest sse_decode_export_project_bundle_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputZipPath = sse_decode_String(deserializer);
    var var_projects = sse_decode_list_project_bundle_source(deserializer);
    return ExportProjectBundleRequest(
      outputZipPath: var_outputZipPath,
      projects: var_projects,
    );
  }

  @protected
  ExportProjectRequest sse_decode_export_project_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectId = sse_decode_String(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_projectDescription = sse_decode_opt_String(deserializer);
    var var_projectCreatedAt = sse_decode_String(deserializer);
    var var_snapshotAt = sse_decode_String(deserializer);
    var var_omittedProcessingCount = sse_decode_u_32(deserializer);
    var var_omittedFailedCount = sse_decode_u_32(deserializer);
    var var_outputZipPath = sse_decode_String(deserializer);
    var var_includeOriginals = sse_decode_bool(deserializer);
    var var_watermark = sse_decode_export_watermark_settings(deserializer);
    var var_photos = sse_decode_list_export_photo_record(deserializer);
    var var_templates = sse_decode_list_export_capture_template(deserializer);
    return ExportProjectRequest(
      projectId: var_projectId,
      projectName: var_projectName,
      projectDescription: var_projectDescription,
      projectCreatedAt: var_projectCreatedAt,
      snapshotAt: var_snapshotAt,
      omittedProcessingCount: var_omittedProcessingCount,
      omittedFailedCount: var_omittedFailedCount,
      outputZipPath: var_outputZipPath,
      includeOriginals: var_includeOriginals,
      watermark: var_watermark,
      photos: var_photos,
      templates: var_templates,
    );
  }

  @protected
  ExportProjectResult sse_decode_export_project_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputZipPath = sse_decode_String(deserializer);
    var var_archiveSha256 = sse_decode_String(deserializer);
    var var_photoCount = sse_decode_u_32(deserializer);
    return ExportProjectResult(
      outputZipPath: var_outputZipPath,
      archiveSha256: var_archiveSha256,
      photoCount: var_photoCount,
    );
  }

  @protected
  ExportSelectionProject sse_decode_export_selection_project(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectId = sse_decode_String(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_photos = sse_decode_list_export_photo_record(deserializer);
    return ExportSelectionProject(
      projectId: var_projectId,
      projectName: var_projectName,
      photos: var_photos,
    );
  }

  @protected
  ExportSelectionRequest sse_decode_export_selection_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputZipPath = sse_decode_String(deserializer);
    var var_includeOriginals = sse_decode_bool(deserializer);
    var var_projects = sse_decode_list_export_selection_project(deserializer);
    return ExportSelectionRequest(
      outputZipPath: var_outputZipPath,
      includeOriginals: var_includeOriginals,
      projects: var_projects,
    );
  }

  @protected
  ExportWatermarkSettings sse_decode_export_watermark_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_position = sse_decode_String(deserializer);
    var var_opacity = sse_decode_f_64(deserializer);
    var var_accentColorArgb = sse_decode_u_32(deserializer);
    var var_fontScale = sse_decode_f_64(deserializer);
    return ExportWatermarkSettings(
      position: var_position,
      opacity: var_opacity,
      accentColorArgb: var_accentColorArgb,
      fontScale: var_fontScale,
    );
  }

  @protected
  ExtractArchivePhotoRequest sse_decode_extract_archive_photo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_zipPath = sse_decode_String(deserializer);
    var var_photoNumber = sse_decode_String(deserializer);
    var var_renderedDestination = sse_decode_String(deserializer);
    var var_originalDestination = sse_decode_opt_String(deserializer);
    return ExtractArchivePhotoRequest(
      zipPath: var_zipPath,
      photoNumber: var_photoNumber,
      renderedDestination: var_renderedDestination,
      originalDestination: var_originalDestination,
    );
  }

  @protected
  ExtractProjectBundleEntryRequest
  sse_decode_extract_project_bundle_entry_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_zipPath = sse_decode_String(deserializer);
    var var_archivePath = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    return ExtractProjectBundleEntryRequest(
      zipPath: var_zipPath,
      archivePath: var_archivePath,
      outputPath: var_outputPath,
    );
  }

  @protected
  ExtractedArchivePhoto sse_decode_extracted_archive_photo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_renderedPath = sse_decode_String(deserializer);
    var var_originalPath = sse_decode_opt_String(deserializer);
    return ExtractedArchivePhoto(
      renderedPath: var_renderedPath,
      originalPath: var_originalPath,
    );
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<ArchiveCaptureTemplate> sse_decode_list_archive_capture_template(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArchiveCaptureTemplate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_archive_capture_template(deserializer));
    }
    return ans_;
  }

  @protected
  List<ArchivePhotoPreview> sse_decode_list_archive_photo_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ArchivePhotoPreview>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_archive_photo_preview(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExportCaptureTemplate> sse_decode_list_export_capture_template(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExportCaptureTemplate>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_export_capture_template(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExportPhotoRecord> sse_decode_list_export_photo_record(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExportPhotoRecord>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_export_photo_record(deserializer));
    }
    return ans_;
  }

  @protected
  List<ExportSelectionProject> sse_decode_list_export_selection_project(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ExportSelectionProject>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_export_selection_project(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProjectBundleEntryPreview> sse_decode_list_project_bundle_entry_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectBundleEntryPreview>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_bundle_entry_preview(deserializer));
    }
    return ans_;
  }

  @protected
  List<ProjectBundleSource> sse_decode_list_project_bundle_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectBundleSource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_bundle_source(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ArchiveWatermarkSettings?
  sse_decode_opt_box_autoadd_archive_watermark_settings(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_archive_watermark_settings(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProjectArchivePreview sse_decode_project_archive_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schemaVersion = sse_decode_u_32(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_projectDescription = sse_decode_opt_String(deserializer);
    var var_projectCreatedAt = sse_decode_opt_String(deserializer);
    var var_snapshotAt = sse_decode_opt_String(deserializer);
    var var_omittedProcessingCount = sse_decode_u_32(deserializer);
    var var_omittedFailedCount = sse_decode_u_32(deserializer);
    var var_isPartial = sse_decode_bool(deserializer);
    var var_includesOriginals = sse_decode_bool(deserializer);
    var var_watermark = sse_decode_opt_box_autoadd_archive_watermark_settings(
      deserializer,
    );
    var var_photos = sse_decode_list_archive_photo_preview(deserializer);
    var var_templates = sse_decode_list_archive_capture_template(deserializer);
    return ProjectArchivePreview(
      schemaVersion: var_schemaVersion,
      projectName: var_projectName,
      projectDescription: var_projectDescription,
      projectCreatedAt: var_projectCreatedAt,
      snapshotAt: var_snapshotAt,
      omittedProcessingCount: var_omittedProcessingCount,
      omittedFailedCount: var_omittedFailedCount,
      isPartial: var_isPartial,
      includesOriginals: var_includesOriginals,
      watermark: var_watermark,
      photos: var_photos,
      templates: var_templates,
    );
  }

  @protected
  ProjectBundleEntryPreview sse_decode_project_bundle_entry_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectId = sse_decode_String(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_archivePath = sse_decode_String(deserializer);
    var var_archiveSha256 = sse_decode_String(deserializer);
    return ProjectBundleEntryPreview(
      projectId: var_projectId,
      projectName: var_projectName,
      archivePath: var_archivePath,
      archiveSha256: var_archiveSha256,
    );
  }

  @protected
  ProjectBundlePreview sse_decode_project_bundle_preview(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_schemaVersion = sse_decode_u_32(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_projects = sse_decode_list_project_bundle_entry_preview(
      deserializer,
    );
    return ProjectBundlePreview(
      schemaVersion: var_schemaVersion,
      createdAt: var_createdAt,
      projects: var_projects,
    );
  }

  @protected
  ProjectBundleSource sse_decode_project_bundle_source(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_projectId = sse_decode_String(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_archivePath = sse_decode_String(deserializer);
    return ProjectBundleSource(
      projectId: var_projectId,
      projectName: var_projectName,
      archivePath: var_archivePath,
    );
  }

  @protected
  RenderPhotoRequest sse_decode_render_photo_request(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourcePath = sse_decode_String(deserializer);
    var var_outputPath = sse_decode_String(deserializer);
    var var_projectName = sse_decode_String(deserializer);
    var var_workLocation = sse_decode_String(deserializer);
    var var_workContent = sse_decode_String(deserializer);
    var var_photographer = sse_decode_String(deserializer);
    var var_photoNumber = sse_decode_String(deserializer);
    var var_capturedAt = sse_decode_String(deserializer);
    var var_address = sse_decode_opt_String(deserializer);
    var var_coordinates = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    var var_position = sse_decode_watermark_position(deserializer);
    var var_opacity = sse_decode_f_64(deserializer);
    var var_accentColorArgb = sse_decode_u_32(deserializer);
    var var_fontScale = sse_decode_f_64(deserializer);
    var var_localeCode = sse_decode_String(deserializer);
    return RenderPhotoRequest(
      sourcePath: var_sourcePath,
      outputPath: var_outputPath,
      projectName: var_projectName,
      workLocation: var_workLocation,
      workContent: var_workContent,
      photographer: var_photographer,
      photoNumber: var_photoNumber,
      capturedAt: var_capturedAt,
      address: var_address,
      coordinates: var_coordinates,
      notes: var_notes,
      position: var_position,
      opacity: var_opacity,
      accentColorArgb: var_accentColorArgb,
      fontScale: var_fontScale,
      localeCode: var_localeCode,
    );
  }

  @protected
  RenderPhotoResult sse_decode_render_photo_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_outputPath = sse_decode_String(deserializer);
    var var_outputSha256 = sse_decode_String(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return RenderPhotoResult(
      outputPath: var_outputPath,
      outputSha256: var_outputSha256,
      width: var_width,
      height: var_height,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WatermarkPosition sse_decode_watermark_position(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return WatermarkPosition.values[inner];
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_archive_capture_template(
    ArchiveCaptureTemplate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.workLocation, serializer);
    sse_encode_String(self.workContent, serializer);
    sse_encode_String(self.photographer, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_archive_photo_preview(
    ArchivePhotoPreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.photoNumber, serializer);
    sse_encode_bool(self.hasOriginal, serializer);
    sse_encode_String(self.originalSha256, serializer);
    sse_encode_String(self.capturedAt, serializer);
    sse_encode_String(self.workLocation, serializer);
    sse_encode_String(self.workContent, serializer);
    sse_encode_String(self.photographer, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_opt_box_autoadd_f_64(self.latitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.longitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.accuracyMeters, serializer);
    sse_encode_opt_String(self.watermarkLocaleCode, serializer);
  }

  @protected
  void sse_encode_archive_watermark_settings(
    ArchiveWatermarkSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.position, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_u_32(self.accentColorArgb, serializer);
    sse_encode_f_64(self.fontScale, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_archive_watermark_settings(
    ArchiveWatermarkSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_archive_watermark_settings(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_export_project_bundle_request(
    ExportProjectBundleRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_project_bundle_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_project_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_export_selection_request(
    ExportSelectionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_export_selection_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_extract_archive_photo_request(
    ExtractArchivePhotoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_extract_archive_photo_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_extract_project_bundle_entry_request(
    ExtractProjectBundleEntryRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_extract_project_bundle_entry_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_render_photo_request(self, serializer);
  }

  @protected
  void sse_encode_export_capture_template(
    ExportCaptureTemplate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.workLocation, serializer);
    sse_encode_String(self.workContent, serializer);
    sse_encode_String(self.photographer, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_String(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_export_photo_record(
    ExportPhotoRecord self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.photoNumber, serializer);
    sse_encode_String(self.watermarkedPath, serializer);
    sse_encode_opt_String(self.originalPath, serializer);
    sse_encode_String(self.originalSha256, serializer);
    sse_encode_String(self.capturedAt, serializer);
    sse_encode_String(self.workLocation, serializer);
    sse_encode_String(self.workContent, serializer);
    sse_encode_String(self.photographer, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.coordinates, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_opt_box_autoadd_f_64(self.latitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.longitude, serializer);
    sse_encode_opt_box_autoadd_f_64(self.accuracyMeters, serializer);
    sse_encode_opt_String(self.watermarkLocaleCode, serializer);
  }

  @protected
  void sse_encode_export_project_bundle_request(
    ExportProjectBundleRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputZipPath, serializer);
    sse_encode_list_project_bundle_source(self.projects, serializer);
  }

  @protected
  void sse_encode_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectId, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_opt_String(self.projectDescription, serializer);
    sse_encode_String(self.projectCreatedAt, serializer);
    sse_encode_String(self.snapshotAt, serializer);
    sse_encode_u_32(self.omittedProcessingCount, serializer);
    sse_encode_u_32(self.omittedFailedCount, serializer);
    sse_encode_String(self.outputZipPath, serializer);
    sse_encode_bool(self.includeOriginals, serializer);
    sse_encode_export_watermark_settings(self.watermark, serializer);
    sse_encode_list_export_photo_record(self.photos, serializer);
    sse_encode_list_export_capture_template(self.templates, serializer);
  }

  @protected
  void sse_encode_export_project_result(
    ExportProjectResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputZipPath, serializer);
    sse_encode_String(self.archiveSha256, serializer);
    sse_encode_u_32(self.photoCount, serializer);
  }

  @protected
  void sse_encode_export_selection_project(
    ExportSelectionProject self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectId, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_list_export_photo_record(self.photos, serializer);
  }

  @protected
  void sse_encode_export_selection_request(
    ExportSelectionRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputZipPath, serializer);
    sse_encode_bool(self.includeOriginals, serializer);
    sse_encode_list_export_selection_project(self.projects, serializer);
  }

  @protected
  void sse_encode_export_watermark_settings(
    ExportWatermarkSettings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.position, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_u_32(self.accentColorArgb, serializer);
    sse_encode_f_64(self.fontScale, serializer);
  }

  @protected
  void sse_encode_extract_archive_photo_request(
    ExtractArchivePhotoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.zipPath, serializer);
    sse_encode_String(self.photoNumber, serializer);
    sse_encode_String(self.renderedDestination, serializer);
    sse_encode_opt_String(self.originalDestination, serializer);
  }

  @protected
  void sse_encode_extract_project_bundle_entry_request(
    ExtractProjectBundleEntryRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.zipPath, serializer);
    sse_encode_String(self.archivePath, serializer);
    sse_encode_String(self.outputPath, serializer);
  }

  @protected
  void sse_encode_extracted_archive_photo(
    ExtractedArchivePhoto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.renderedPath, serializer);
    sse_encode_opt_String(self.originalPath, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_archive_capture_template(
    List<ArchiveCaptureTemplate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_archive_capture_template(item, serializer);
    }
  }

  @protected
  void sse_encode_list_archive_photo_preview(
    List<ArchivePhotoPreview> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_archive_photo_preview(item, serializer);
    }
  }

  @protected
  void sse_encode_list_export_capture_template(
    List<ExportCaptureTemplate> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_export_capture_template(item, serializer);
    }
  }

  @protected
  void sse_encode_list_export_photo_record(
    List<ExportPhotoRecord> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_export_photo_record(item, serializer);
    }
  }

  @protected
  void sse_encode_list_export_selection_project(
    List<ExportSelectionProject> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_export_selection_project(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_project_bundle_entry_preview(
    List<ProjectBundleEntryPreview> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_bundle_entry_preview(item, serializer);
    }
  }

  @protected
  void sse_encode_list_project_bundle_source(
    List<ProjectBundleSource> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_bundle_source(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_archive_watermark_settings(
    ArchiveWatermarkSettings? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_archive_watermark_settings(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_project_archive_preview(
    ProjectArchivePreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.schemaVersion, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_opt_String(self.projectDescription, serializer);
    sse_encode_opt_String(self.projectCreatedAt, serializer);
    sse_encode_opt_String(self.snapshotAt, serializer);
    sse_encode_u_32(self.omittedProcessingCount, serializer);
    sse_encode_u_32(self.omittedFailedCount, serializer);
    sse_encode_bool(self.isPartial, serializer);
    sse_encode_bool(self.includesOriginals, serializer);
    sse_encode_opt_box_autoadd_archive_watermark_settings(
      self.watermark,
      serializer,
    );
    sse_encode_list_archive_photo_preview(self.photos, serializer);
    sse_encode_list_archive_capture_template(self.templates, serializer);
  }

  @protected
  void sse_encode_project_bundle_entry_preview(
    ProjectBundleEntryPreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectId, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_String(self.archivePath, serializer);
    sse_encode_String(self.archiveSha256, serializer);
  }

  @protected
  void sse_encode_project_bundle_preview(
    ProjectBundlePreview self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.schemaVersion, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_list_project_bundle_entry_preview(self.projects, serializer);
  }

  @protected
  void sse_encode_project_bundle_source(
    ProjectBundleSource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.projectId, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_String(self.archivePath, serializer);
  }

  @protected
  void sse_encode_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourcePath, serializer);
    sse_encode_String(self.outputPath, serializer);
    sse_encode_String(self.projectName, serializer);
    sse_encode_String(self.workLocation, serializer);
    sse_encode_String(self.workContent, serializer);
    sse_encode_String(self.photographer, serializer);
    sse_encode_String(self.photoNumber, serializer);
    sse_encode_String(self.capturedAt, serializer);
    sse_encode_opt_String(self.address, serializer);
    sse_encode_opt_String(self.coordinates, serializer);
    sse_encode_opt_String(self.notes, serializer);
    sse_encode_watermark_position(self.position, serializer);
    sse_encode_f_64(self.opacity, serializer);
    sse_encode_u_32(self.accentColorArgb, serializer);
    sse_encode_f_64(self.fontScale, serializer);
    sse_encode_String(self.localeCode, serializer);
  }

  @protected
  void sse_encode_render_photo_result(
    RenderPhotoResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.outputPath, serializer);
    sse_encode_String(self.outputSha256, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_watermark_position(
    WatermarkPosition self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
