// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/image_core.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ArchiveCaptureTemplate dco_decode_archive_capture_template(dynamic raw);

  @protected
  ArchivePhotoPreview dco_decode_archive_photo_preview(dynamic raw);

  @protected
  ArchiveWatermarkSettings dco_decode_archive_watermark_settings(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ArchiveWatermarkSettings dco_decode_box_autoadd_archive_watermark_settings(
    dynamic raw,
  );

  @protected
  ExportProjectBundleRequest
  dco_decode_box_autoadd_export_project_bundle_request(dynamic raw);

  @protected
  ExportProjectRequest dco_decode_box_autoadd_export_project_request(
    dynamic raw,
  );

  @protected
  ExportSelectionRequest dco_decode_box_autoadd_export_selection_request(
    dynamic raw,
  );

  @protected
  ExtractArchivePhotoRequest
  dco_decode_box_autoadd_extract_archive_photo_request(dynamic raw);

  @protected
  ExtractProjectBundleEntryRequest
  dco_decode_box_autoadd_extract_project_bundle_entry_request(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  RenderPhotoRequest dco_decode_box_autoadd_render_photo_request(dynamic raw);

  @protected
  ExportCaptureTemplate dco_decode_export_capture_template(dynamic raw);

  @protected
  ExportPhotoRecord dco_decode_export_photo_record(dynamic raw);

  @protected
  ExportProjectBundleRequest dco_decode_export_project_bundle_request(
    dynamic raw,
  );

  @protected
  ExportProjectRequest dco_decode_export_project_request(dynamic raw);

  @protected
  ExportProjectResult dco_decode_export_project_result(dynamic raw);

  @protected
  ExportSelectionProject dco_decode_export_selection_project(dynamic raw);

  @protected
  ExportSelectionRequest dco_decode_export_selection_request(dynamic raw);

  @protected
  ExportWatermarkSettings dco_decode_export_watermark_settings(dynamic raw);

  @protected
  ExtractArchivePhotoRequest dco_decode_extract_archive_photo_request(
    dynamic raw,
  );

  @protected
  ExtractProjectBundleEntryRequest
  dco_decode_extract_project_bundle_entry_request(dynamic raw);

  @protected
  ExtractedArchivePhoto dco_decode_extracted_archive_photo(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ArchiveCaptureTemplate> dco_decode_list_archive_capture_template(
    dynamic raw,
  );

  @protected
  List<ArchivePhotoPreview> dco_decode_list_archive_photo_preview(dynamic raw);

  @protected
  List<ExportCaptureTemplate> dco_decode_list_export_capture_template(
    dynamic raw,
  );

  @protected
  List<ExportPhotoRecord> dco_decode_list_export_photo_record(dynamic raw);

  @protected
  List<ExportSelectionProject> dco_decode_list_export_selection_project(
    dynamic raw,
  );

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectBundleEntryPreview> dco_decode_list_project_bundle_entry_preview(
    dynamic raw,
  );

  @protected
  List<ProjectBundleSource> dco_decode_list_project_bundle_source(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ArchiveWatermarkSettings?
  dco_decode_opt_box_autoadd_archive_watermark_settings(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  ProjectArchivePreview dco_decode_project_archive_preview(dynamic raw);

  @protected
  ProjectBundleEntryPreview dco_decode_project_bundle_entry_preview(
    dynamic raw,
  );

  @protected
  ProjectBundlePreview dco_decode_project_bundle_preview(dynamic raw);

  @protected
  ProjectBundleSource dco_decode_project_bundle_source(dynamic raw);

  @protected
  RenderPhotoRequest dco_decode_render_photo_request(dynamic raw);

  @protected
  RenderPhotoResult dco_decode_render_photo_result(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  WatermarkPosition dco_decode_watermark_position(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ArchiveCaptureTemplate sse_decode_archive_capture_template(
    SseDeserializer deserializer,
  );

  @protected
  ArchivePhotoPreview sse_decode_archive_photo_preview(
    SseDeserializer deserializer,
  );

  @protected
  ArchiveWatermarkSettings sse_decode_archive_watermark_settings(
    SseDeserializer deserializer,
  );

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ArchiveWatermarkSettings sse_decode_box_autoadd_archive_watermark_settings(
    SseDeserializer deserializer,
  );

  @protected
  ExportProjectBundleRequest
  sse_decode_box_autoadd_export_project_bundle_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportProjectRequest sse_decode_box_autoadd_export_project_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportSelectionRequest sse_decode_box_autoadd_export_selection_request(
    SseDeserializer deserializer,
  );

  @protected
  ExtractArchivePhotoRequest
  sse_decode_box_autoadd_extract_archive_photo_request(
    SseDeserializer deserializer,
  );

  @protected
  ExtractProjectBundleEntryRequest
  sse_decode_box_autoadd_extract_project_bundle_entry_request(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  RenderPhotoRequest sse_decode_box_autoadd_render_photo_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportCaptureTemplate sse_decode_export_capture_template(
    SseDeserializer deserializer,
  );

  @protected
  ExportPhotoRecord sse_decode_export_photo_record(
    SseDeserializer deserializer,
  );

  @protected
  ExportProjectBundleRequest sse_decode_export_project_bundle_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportProjectRequest sse_decode_export_project_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportProjectResult sse_decode_export_project_result(
    SseDeserializer deserializer,
  );

  @protected
  ExportSelectionProject sse_decode_export_selection_project(
    SseDeserializer deserializer,
  );

  @protected
  ExportSelectionRequest sse_decode_export_selection_request(
    SseDeserializer deserializer,
  );

  @protected
  ExportWatermarkSettings sse_decode_export_watermark_settings(
    SseDeserializer deserializer,
  );

  @protected
  ExtractArchivePhotoRequest sse_decode_extract_archive_photo_request(
    SseDeserializer deserializer,
  );

  @protected
  ExtractProjectBundleEntryRequest
  sse_decode_extract_project_bundle_entry_request(SseDeserializer deserializer);

  @protected
  ExtractedArchivePhoto sse_decode_extracted_archive_photo(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ArchiveCaptureTemplate> sse_decode_list_archive_capture_template(
    SseDeserializer deserializer,
  );

  @protected
  List<ArchivePhotoPreview> sse_decode_list_archive_photo_preview(
    SseDeserializer deserializer,
  );

  @protected
  List<ExportCaptureTemplate> sse_decode_list_export_capture_template(
    SseDeserializer deserializer,
  );

  @protected
  List<ExportPhotoRecord> sse_decode_list_export_photo_record(
    SseDeserializer deserializer,
  );

  @protected
  List<ExportSelectionProject> sse_decode_list_export_selection_project(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectBundleEntryPreview> sse_decode_list_project_bundle_entry_preview(
    SseDeserializer deserializer,
  );

  @protected
  List<ProjectBundleSource> sse_decode_list_project_bundle_source(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ArchiveWatermarkSettings?
  sse_decode_opt_box_autoadd_archive_watermark_settings(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  ProjectArchivePreview sse_decode_project_archive_preview(
    SseDeserializer deserializer,
  );

  @protected
  ProjectBundleEntryPreview sse_decode_project_bundle_entry_preview(
    SseDeserializer deserializer,
  );

  @protected
  ProjectBundlePreview sse_decode_project_bundle_preview(
    SseDeserializer deserializer,
  );

  @protected
  ProjectBundleSource sse_decode_project_bundle_source(
    SseDeserializer deserializer,
  );

  @protected
  RenderPhotoRequest sse_decode_render_photo_request(
    SseDeserializer deserializer,
  );

  @protected
  RenderPhotoResult sse_decode_render_photo_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  WatermarkPosition sse_decode_watermark_position(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_archive_capture_template(
    ArchiveCaptureTemplate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_photo_preview(
    ArchivePhotoPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_archive_watermark_settings(
    ArchiveWatermarkSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_archive_watermark_settings(
    ArchiveWatermarkSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_project_bundle_request(
    ExportProjectBundleRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_export_selection_request(
    ExportSelectionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_extract_archive_photo_request(
    ExtractArchivePhotoRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_extract_project_bundle_entry_request(
    ExtractProjectBundleEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_capture_template(
    ExportCaptureTemplate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_photo_record(
    ExportPhotoRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_project_bundle_request(
    ExportProjectBundleRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_project_request(
    ExportProjectRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_project_result(
    ExportProjectResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_selection_project(
    ExportSelectionProject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_selection_request(
    ExportSelectionRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_watermark_settings(
    ExportWatermarkSettings self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_extract_archive_photo_request(
    ExtractArchivePhotoRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_extract_project_bundle_entry_request(
    ExtractProjectBundleEntryRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_extracted_archive_photo(
    ExtractedArchivePhoto self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_archive_capture_template(
    List<ArchiveCaptureTemplate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_archive_photo_preview(
    List<ArchivePhotoPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_export_capture_template(
    List<ExportCaptureTemplate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_export_photo_record(
    List<ExportPhotoRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_export_selection_project(
    List<ExportSelectionProject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_bundle_entry_preview(
    List<ProjectBundleEntryPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_bundle_source(
    List<ProjectBundleSource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_archive_watermark_settings(
    ArchiveWatermarkSettings? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_project_archive_preview(
    ProjectArchivePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_bundle_entry_preview(
    ProjectBundleEntryPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_bundle_preview(
    ProjectBundlePreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_project_bundle_source(
    ProjectBundleSource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_render_photo_request(
    RenderPhotoRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_render_photo_result(
    RenderPhotoResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_watermark_position(
    WatermarkPosition self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
