// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Connection parameters. The password is only ever held in memory here; it
/// is supplied per call from secure storage and never persisted in SQLite.
class NasConfig {
  final NasProtocol protocol;
  final String host;
  final int? port;
  final String username;
  final String password;

  /// WebDAV/SFTP: server path prefix such as `/SiteMark`. SMB: `/share`
  /// followed by optional sub-directories such as `/media/SiteMark`.
  final String rootPath;

  /// WebDAV only: try HTTPS instead of HTTP. SFTP is always encrypted and
  /// SMB negotiates its own crypto, so both ignore this flag.
  final bool secureTls;

  /// WebDAV only: accept self-signed or mismatched certificates.
  final bool acceptInvalidTls;

  /// SFTP only: host key fingerprint previously accepted by the user
  /// (OpenSSH `SHA256:…` form). `None` trusts on first use; a mismatch
  /// aborts every operation with `NasErrorCode::HostKeyChanged`.
  final String? knownSftpFingerprint;

  const NasConfig({
    required this.protocol,
    required this.host,
    this.port,
    required this.username,
    required this.password,
    required this.rootPath,
    required this.secureTls,
    required this.acceptInvalidTls,
    this.knownSftpFingerprint,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^
      host.hashCode ^
      port.hashCode ^
      username.hashCode ^
      password.hashCode ^
      rootPath.hashCode ^
      secureTls.hashCode ^
      acceptInvalidTls.hashCode ^
      knownSftpFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NasConfig &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          host == other.host &&
          port == other.port &&
          username == other.username &&
          password == other.password &&
          rootPath == other.rootPath &&
          secureTls == other.secureTls &&
          acceptInvalidTls == other.acceptInvalidTls &&
          knownSftpFingerprint == other.knownSftpFingerprint;
}

class NasError implements FrbException {
  final NasErrorCode code;

  const NasError({required this.code});

  @override
  int get hashCode => code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NasError &&
          runtimeType == other.runtimeType &&
          code == other.code;
}

/// Stable, translatable failure categories. UI text must map from these —
/// never from server messages.
enum NasErrorCode {
  configInvalid,
  connectionFailed,
  authFailed,
  timeout,
  tlsError,

  /// HTTPS was requested on a build whose WebDAV stack has no TLS support
  /// (the HarmonyOS line stays C-free and therefore TLS-free for WebDAV).
  tlsUnsupported,

  /// SFTP server key does not match the fingerprint the user accepted.
  hostKeyChanged,
  protocolError,
  quotaInsufficient,
  pathInvalid,
  localIo,
}

/// Remote surface selection. Wire values are serialized snake_case.
enum NasProtocol { webdav, sftp, smb }

/// Protocol-specific details reported by a successful connection test.
class NasTestDetails {
  /// SFTP: the host key fingerprint observed during the probe, so the
  /// caller can store it after the user accepts the first connection.
  final String? sftpFingerprint;

  const NasTestDetails({this.sftpFingerprint});

  @override
  int get hashCode => sftpFingerprint.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NasTestDetails &&
          runtimeType == other.runtimeType &&
          sftpFingerprint == other.sftpFingerprint;
}
