export class Routes {
  static readonly PROJECT_DETAIL: string = 'projectDetail';
  static readonly PROJECT_EDITOR: string = 'projectEditor';
  static readonly PROJECT_SETTINGS: string = 'projectSettings';
  static readonly CAPTURE_FORM: string = 'captureForm';
  static readonly CAPTURE_DETAIL: string = 'captureDetail';
  static readonly CAPTURE_EDITOR: string = 'captureEditor';
  static readonly PHOTO_VIEWER: string = 'photoViewer';
  static readonly BACKUP: string = 'backup';
  static readonly STORAGE: string = 'storage';
  static readonly DIAGNOSTICS: string = 'diagnostics';
  static readonly APPEARANCE: string = 'appearance';
  static readonly ABOUT: string = 'about';
}
