// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package io.github.wikg1018.sitemark.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object SystemApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class CameraOutcome(val raw: Int) {
  CAPTURED(0),
  CANCELLED(1),
  FAILED(2);

  companion object {
    fun ofRaw(raw: Int): CameraOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class LocationOutcome(val raw: Int) {
  PRECISE(0),
  APPROXIMATE(1),
  PERMISSION_DENIED(2),
  SERVICES_DISABLED(3),
  TIMEOUT(4),
  UNAVAILABLE(5);

  companion object {
    fun ofRaw(raw: Int): LocationOutcome? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CameraCaptureResult (
  val outcome: CameraOutcome,
  val outputPath: String,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CameraCaptureResult {
      val outcome = pigeonVar_list[0] as CameraOutcome
      val outputPath = pigeonVar_list[1] as String
      val errorMessage = pigeonVar_list[2] as String?
      return CameraCaptureResult(outcome, outputPath, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outcome,
      outputPath,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CameraCaptureResult
    return SystemApiPigeonUtils.deepEquals(this.outcome, other.outcome) && SystemApiPigeonUtils.deepEquals(this.outputPath, other.outputPath) && SystemApiPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.outcome)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "CameraCaptureResult(outcome=$outcome, outputPath=$outputPath, errorMessage=$errorMessage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RecoveredCameraCapture (
  val captureId: String,
  val outputPath: String,
  val hasContent: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RecoveredCameraCapture {
      val captureId = pigeonVar_list[0] as String
      val outputPath = pigeonVar_list[1] as String
      val hasContent = pigeonVar_list[2] as Boolean
      return RecoveredCameraCapture(captureId, outputPath, hasContent)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      captureId,
      outputPath,
      hasContent,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RecoveredCameraCapture
    return SystemApiPigeonUtils.deepEquals(this.captureId, other.captureId) && SystemApiPigeonUtils.deepEquals(this.outputPath, other.outputPath) && SystemApiPigeonUtils.deepEquals(this.hasContent, other.hasContent)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.captureId)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.hasContent)
    return result
  }
  override fun toString(): String {
    return "RecoveredCameraCapture(captureId=$captureId, outputPath=$outputPath, hasContent=$hasContent)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class LocationResult (
  val outcome: LocationOutcome,
  val latitude: Double? = null,
  val longitude: Double? = null,
  val accuracyMeters: Double? = null,
  val address: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LocationResult {
      val outcome = pigeonVar_list[0] as LocationOutcome
      val latitude = pigeonVar_list[1] as Double?
      val longitude = pigeonVar_list[2] as Double?
      val accuracyMeters = pigeonVar_list[3] as Double?
      val address = pigeonVar_list[4] as String?
      val errorMessage = pigeonVar_list[5] as String?
      return LocationResult(outcome, latitude, longitude, accuracyMeters, address, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      outcome,
      latitude,
      longitude,
      accuracyMeters,
      address,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LocationResult
    return SystemApiPigeonUtils.deepEquals(this.outcome, other.outcome) && SystemApiPigeonUtils.deepEquals(this.latitude, other.latitude) && SystemApiPigeonUtils.deepEquals(this.longitude, other.longitude) && SystemApiPigeonUtils.deepEquals(this.accuracyMeters, other.accuracyMeters) && SystemApiPigeonUtils.deepEquals(this.address, other.address) && SystemApiPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.outcome)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.latitude)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.longitude)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.accuracyMeters)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.address)
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "LocationResult(outcome=$outcome, latitude=$latitude, longitude=$longitude, accuracyMeters=$accuracyMeters, address=$address, errorMessage=$errorMessage)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaPublishResult (
  val contentUri: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaPublishResult {
      val contentUri = pigeonVar_list[0] as String
      return MediaPublishResult(contentUri)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      contentUri,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaPublishResult
    return SystemApiPigeonUtils.deepEquals(this.contentUri, other.contentUri)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + SystemApiPigeonUtils.deepHash(this.contentUri)
    return result
  }
  override fun toString(): String {
    return "MediaPublishResult(contentUri=$contentUri)"
  }
}
private open class SystemApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CameraOutcome.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          LocationOutcome.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CameraCaptureResult.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RecoveredCameraCapture.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LocationResult.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaPublishResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is CameraOutcome -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is LocationOutcome -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is CameraCaptureResult -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is RecoveredCameraCapture -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is LocationResult -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is MediaPublishResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface SiteMarkSystemApi {
  fun createCameraTarget(captureId: String): String
  fun launchCamera(captureId: String, callback: (Result<CameraCaptureResult>) -> Unit)
  fun recoverCameraCapture(): RecoveredCameraCapture?
  fun finishCameraCapture(captureId: String, keepOriginal: Boolean)
  fun requestCurrentLocation(timeoutMillis: Long, callback: (Result<LocationResult>) -> Unit)
  fun publishJpeg(sourcePath: String, displayName: String, callback: (Result<MediaPublishResult>) -> Unit)
  fun deletePublishedImage(contentUri: String, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by SiteMarkSystemApi. */
    val codec: MessageCodec<Any?> by lazy {
      SystemApiPigeonCodec()
    }
    /** Sets up an instance of `SiteMarkSystemApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: SiteMarkSystemApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sitemark.SiteMarkSystemApi.createCameraTarget$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val captureIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.createCameraTarget(captureIdArg))
            } catch (exception: Throwable) {
              SystemApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sitemark.SiteMarkSystemApi.launchCamera$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val captureIdArg = args[0] as String
            api.launchCamera(captureIdArg) { result: Result<CameraCaptureResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SystemApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SystemApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sitemark.SiteMarkSystemApi.recoverCameraCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.recoverCameraCapture())
            } catch (exception: Throwable) {
              SystemApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sitemark.SiteMarkSystemApi.finishCameraCapture$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val captureIdArg = args[0] as String
            val keepOriginalArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.finishCameraCapture(captureIdArg, keepOriginalArg)
              listOf(null)
            } catch (exception: Throwable) {
              SystemApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sitemark.SiteMarkSystemApi.requestCurrentLocation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val timeoutMillisArg = args[0] as Long
            api.requestCurrentLocation(timeoutMillisArg) { result: Result<LocationResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SystemApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SystemApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sitemark.SiteMarkSystemApi.publishJpeg$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sourcePathArg = args[0] as String
            val displayNameArg = args[1] as String
            api.publishJpeg(sourcePathArg, displayNameArg) { result: Result<MediaPublishResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SystemApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(SystemApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.sitemark.SiteMarkSystemApi.deletePublishedImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val contentUriArg = args[0] as String
            api.deletePublishedImage(contentUriArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(SystemApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(SystemApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
