// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_file_to_zip`, `argb_to_rgba`, `blend_rect`, `commit_bundle_temporary_no_replace`, `commit_render_temporary`, `compute_rendered_lines`, `copy_bundle_entry_to`, `copy_capped`, `draw_watermark_card`, `expected_bundle_archive_path`, `extract_entry_to`, `extract_project_bundle_entry_with_before_commit`, `find_archive_entries`, `hash_bundle_entry`, `image_failure`, `invalid_data`, `io_failure`, `is_dart_regexp_whitespace`, `is_dart_trim_whitespace`, `is_leap_year`, `is_valid_exported_timestamp`, `is_valid_lifecycle_status`, `is_valid_sha256`, `labels`, `layout_for_request`, `logical_watermark_lines`, `non_empty`, `normalize_lifecycle_fields`, `normalized_template_name`, `open_zip`, `parse_two_digits`, `read_project_bundle_manifest`, `read_project_manifest`, `read_text_failure`, `render_photo_with_before_commit`, `safe_archive_component`, `safe_photo_number_component`, `template_name_key`, `tokenize`, `trimmed_template_field`, `unix_time_millis`, `validate_archive_templates`, `validate_project_bundle`, `validate_render_request`, `validate_source_dimensions`, `validate_source_format`, `verify_file`, `wrap_text`, `zip_failure`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CsvRow`, `ExportManifest`, `ManifestCaptureTemplate`, `ManifestPhoto`, `ManifestWatermark`, `ProjectBundleManifestEntry`, `ProjectBundleManifest`, `ProjectManifestFile`, `SelectionManifestProject`, `SelectionManifest`, `WatermarkLabels`, `WatermarkLayout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<String> sha256File({required String path}) =>
    RustLib.instance.api.crateApiImageCoreSha256File(path: path);

Future<RenderPhotoResult> renderPhoto({required RenderPhotoRequest request}) =>
    RustLib.instance.api.crateApiImageCoreRenderPhoto(request: request);

Future<ExportDiagnosticBundleResult> exportDiagnosticBundle({
  required ExportDiagnosticBundleRequest request,
}) => RustLib.instance.api.crateApiImageCoreExportDiagnosticBundle(
  request: request,
);

Future<ExportProjectResult> exportProject({
  required ExportProjectRequest request,
}) => RustLib.instance.api.crateApiImageCoreExportProject(request: request);

Future<ExportProjectResult> exportSelection({
  required ExportSelectionRequest request,
}) => RustLib.instance.api.crateApiImageCoreExportSelection(request: request);

/// Writes a restorable outer bundle from complete, single-project ZIPs.
/// Inner archives are deliberately stored rather than recompressed: this
/// keeps export CPU predictable and makes the outer entry hash a direct hash
/// of the original project archive bytes.
Future<ExportProjectResult> exportProjectBundle({
  required ExportProjectBundleRequest request,
}) =>
    RustLib.instance.api.crateApiImageCoreExportProjectBundle(request: request);

/// Reads a multi-project bundle only after validating its manifest, exact
/// outer entry set, size limits, and every inner project ZIP hash.
Future<ProjectBundlePreview> readProjectBundle({required String zipPath}) =>
    RustLib.instance.api.crateApiImageCoreReadProjectBundle(zipPath: zipPath);

/// Extracts one validated inner project ZIP into a caller-selected staging
/// location. The destination must not already exist, and all bytes are first
/// written to `<destination>.tmp`; only a final hash match permits rename.
Future<void> extractProjectBundleEntry({
  required ExtractProjectBundleEntryRequest request,
}) => RustLib.instance.api.crateApiImageCoreExtractProjectBundleEntry(
  request: request,
);

/// Validates a backup ZIP and returns its restorable content. Only
/// single-project archives (schema v1-v5) are restorable.
Future<ProjectArchivePreview> readProjectArchive({required String zipPath}) =>
    RustLib.instance.api.crateApiImageCoreReadProjectArchive(zipPath: zipPath);

/// Extracts one photo (and its original when requested) from a backup ZIP.
///
/// Everything lands in `<destination>.tmp` first; only after the original's
/// SHA-256 verifies are the files atomically renamed into place. A failure
/// before the first rename removes every temporary file; once the rendered
/// photo has been committed, a later failure leaves it in place and cleans up
/// the original's temporary file.
Future<ExtractedArchivePhoto> extractArchivePhoto({
  required ExtractArchivePhotoRequest request,
}) =>
    RustLib.instance.api.crateApiImageCoreExtractArchivePhoto(request: request);

class ArchiveCaptureTemplate {
  final String name;
  final String workLocation;
  final String workContent;
  final String photographer;
  final String createdAt;
  final String updatedAt;

  const ArchiveCaptureTemplate({
    required this.name,
    required this.workLocation,
    required this.workContent,
    required this.photographer,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      workLocation.hashCode ^
      workContent.hashCode ^
      photographer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveCaptureTemplate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          workLocation == other.workLocation &&
          workContent == other.workContent &&
          photographer == other.photographer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

/// One restorable photo entry from a project backup manifest.
class ArchivePhotoPreview {
  final String photoNumber;
  final bool hasOriginal;
  final String originalSha256;
  final String capturedAt;
  final String workLocation;
  final String workContent;
  final String photographer;
  final String? address;
  final String? notes;
  final double? latitude;
  final double? longitude;
  final double? accuracyMeters;
  final String? watermarkLocaleCode;

  const ArchivePhotoPreview({
    required this.photoNumber,
    required this.hasOriginal,
    required this.originalSha256,
    required this.capturedAt,
    required this.workLocation,
    required this.workContent,
    required this.photographer,
    this.address,
    this.notes,
    this.latitude,
    this.longitude,
    this.accuracyMeters,
    this.watermarkLocaleCode,
  });

  @override
  int get hashCode =>
      photoNumber.hashCode ^
      hasOriginal.hashCode ^
      originalSha256.hashCode ^
      capturedAt.hashCode ^
      workLocation.hashCode ^
      workContent.hashCode ^
      photographer.hashCode ^
      address.hashCode ^
      notes.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      accuracyMeters.hashCode ^
      watermarkLocaleCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchivePhotoPreview &&
          runtimeType == other.runtimeType &&
          photoNumber == other.photoNumber &&
          hasOriginal == other.hasOriginal &&
          originalSha256 == other.originalSha256 &&
          capturedAt == other.capturedAt &&
          workLocation == other.workLocation &&
          workContent == other.workContent &&
          photographer == other.photographer &&
          address == other.address &&
          notes == other.notes &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          accuracyMeters == other.accuracyMeters &&
          watermarkLocaleCode == other.watermarkLocaleCode;
}

/// Watermark template recovered from a v2 manifest.
class ArchiveWatermarkSettings {
  final String position;
  final double opacity;
  final int accentColorArgb;
  final double fontScale;

  const ArchiveWatermarkSettings({
    required this.position,
    required this.opacity,
    required this.accentColorArgb,
    required this.fontScale,
  });

  @override
  int get hashCode =>
      position.hashCode ^
      opacity.hashCode ^
      accentColorArgb.hashCode ^
      fontScale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ArchiveWatermarkSettings &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          opacity == other.opacity &&
          accentColorArgb == other.accentColorArgb &&
          fontScale == other.fontScale;
}

class ExportCaptureTemplate {
  final String name;
  final String workLocation;
  final String workContent;
  final String photographer;
  final String createdAt;
  final String updatedAt;

  const ExportCaptureTemplate({
    required this.name,
    required this.workLocation,
    required this.workContent,
    required this.photographer,
    required this.createdAt,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      workLocation.hashCode ^
      workContent.hashCode ^
      photographer.hashCode ^
      createdAt.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportCaptureTemplate &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          workLocation == other.workLocation &&
          workContent == other.workContent &&
          photographer == other.photographer &&
          createdAt == other.createdAt &&
          updatedAt == other.updatedAt;
}

class ExportDiagnosticBundleRequest {
  final String outputZipPath;
  final String summary;
  final String environmentJson;
  final String eventsJsonl;
  final String manifestJson;

  const ExportDiagnosticBundleRequest({
    required this.outputZipPath,
    required this.summary,
    required this.environmentJson,
    required this.eventsJsonl,
    required this.manifestJson,
  });

  @override
  int get hashCode =>
      outputZipPath.hashCode ^
      summary.hashCode ^
      environmentJson.hashCode ^
      eventsJsonl.hashCode ^
      manifestJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportDiagnosticBundleRequest &&
          runtimeType == other.runtimeType &&
          outputZipPath == other.outputZipPath &&
          summary == other.summary &&
          environmentJson == other.environmentJson &&
          eventsJsonl == other.eventsJsonl &&
          manifestJson == other.manifestJson;
}

class ExportDiagnosticBundleResult {
  final String outputZipPath;
  final String archiveSha256;

  const ExportDiagnosticBundleResult({
    required this.outputZipPath,
    required this.archiveSha256,
  });

  @override
  int get hashCode => outputZipPath.hashCode ^ archiveSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportDiagnosticBundleResult &&
          runtimeType == other.runtimeType &&
          outputZipPath == other.outputZipPath &&
          archiveSha256 == other.archiveSha256;
}

class ExportPhotoRecord {
  final String photoNumber;
  final String watermarkedPath;
  final String? originalPath;
  final String originalSha256;
  final String capturedAt;
  final String workLocation;
  final String workContent;
  final String photographer;
  final String? address;
  final String? coordinates;
  final String? notes;
  final double? latitude;
  final double? longitude;
  final double? accuracyMeters;
  final String? watermarkLocaleCode;

  const ExportPhotoRecord({
    required this.photoNumber,
    required this.watermarkedPath,
    this.originalPath,
    required this.originalSha256,
    required this.capturedAt,
    required this.workLocation,
    required this.workContent,
    required this.photographer,
    this.address,
    this.coordinates,
    this.notes,
    this.latitude,
    this.longitude,
    this.accuracyMeters,
    this.watermarkLocaleCode,
  });

  @override
  int get hashCode =>
      photoNumber.hashCode ^
      watermarkedPath.hashCode ^
      originalPath.hashCode ^
      originalSha256.hashCode ^
      capturedAt.hashCode ^
      workLocation.hashCode ^
      workContent.hashCode ^
      photographer.hashCode ^
      address.hashCode ^
      coordinates.hashCode ^
      notes.hashCode ^
      latitude.hashCode ^
      longitude.hashCode ^
      accuracyMeters.hashCode ^
      watermarkLocaleCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportPhotoRecord &&
          runtimeType == other.runtimeType &&
          photoNumber == other.photoNumber &&
          watermarkedPath == other.watermarkedPath &&
          originalPath == other.originalPath &&
          originalSha256 == other.originalSha256 &&
          capturedAt == other.capturedAt &&
          workLocation == other.workLocation &&
          workContent == other.workContent &&
          photographer == other.photographer &&
          address == other.address &&
          coordinates == other.coordinates &&
          notes == other.notes &&
          latitude == other.latitude &&
          longitude == other.longitude &&
          accuracyMeters == other.accuracyMeters &&
          watermarkLocaleCode == other.watermarkLocaleCode;
}

class ExportProjectBundleRequest {
  final String outputZipPath;
  final List<ProjectBundleSource> projects;

  const ExportProjectBundleRequest({
    required this.outputZipPath,
    required this.projects,
  });

  @override
  int get hashCode => outputZipPath.hashCode ^ projects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportProjectBundleRequest &&
          runtimeType == other.runtimeType &&
          outputZipPath == other.outputZipPath &&
          projects == other.projects;
}

class ExportProjectRequest {
  final String projectId;
  final String projectName;
  final String? projectDescription;
  final String projectCreatedAt;
  final String snapshotAt;
  final int omittedProcessingCount;
  final int omittedFailedCount;
  final String outputZipPath;
  final bool includeOriginals;
  final String projectLifecycleStatus;
  final bool projectIsPinned;
  final ExportWatermarkSettings watermark;
  final List<ExportPhotoRecord> photos;
  final List<ExportCaptureTemplate> templates;

  const ExportProjectRequest({
    required this.projectId,
    required this.projectName,
    this.projectDescription,
    required this.projectCreatedAt,
    required this.snapshotAt,
    required this.omittedProcessingCount,
    required this.omittedFailedCount,
    required this.outputZipPath,
    required this.includeOriginals,
    required this.projectLifecycleStatus,
    required this.projectIsPinned,
    required this.watermark,
    required this.photos,
    required this.templates,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectName.hashCode ^
      projectDescription.hashCode ^
      projectCreatedAt.hashCode ^
      snapshotAt.hashCode ^
      omittedProcessingCount.hashCode ^
      omittedFailedCount.hashCode ^
      outputZipPath.hashCode ^
      includeOriginals.hashCode ^
      projectLifecycleStatus.hashCode ^
      projectIsPinned.hashCode ^
      watermark.hashCode ^
      photos.hashCode ^
      templates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportProjectRequest &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectName == other.projectName &&
          projectDescription == other.projectDescription &&
          projectCreatedAt == other.projectCreatedAt &&
          snapshotAt == other.snapshotAt &&
          omittedProcessingCount == other.omittedProcessingCount &&
          omittedFailedCount == other.omittedFailedCount &&
          outputZipPath == other.outputZipPath &&
          includeOriginals == other.includeOriginals &&
          projectLifecycleStatus == other.projectLifecycleStatus &&
          projectIsPinned == other.projectIsPinned &&
          watermark == other.watermark &&
          photos == other.photos &&
          templates == other.templates;
}

class ExportProjectResult {
  final String outputZipPath;
  final String archiveSha256;
  final int photoCount;

  const ExportProjectResult({
    required this.outputZipPath,
    required this.archiveSha256,
    required this.photoCount,
  });

  @override
  int get hashCode =>
      outputZipPath.hashCode ^ archiveSha256.hashCode ^ photoCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportProjectResult &&
          runtimeType == other.runtimeType &&
          outputZipPath == other.outputZipPath &&
          archiveSha256 == other.archiveSha256 &&
          photoCount == other.photoCount;
}

class ExportSelectionProject {
  final String projectId;
  final String projectName;
  final List<ExportPhotoRecord> photos;

  const ExportSelectionProject({
    required this.projectId,
    required this.projectName,
    required this.photos,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^ projectName.hashCode ^ photos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportSelectionProject &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectName == other.projectName &&
          photos == other.photos;
}

class ExportSelectionRequest {
  final String outputZipPath;
  final bool includeOriginals;
  final List<ExportSelectionProject> projects;

  const ExportSelectionRequest({
    required this.outputZipPath,
    required this.includeOriginals,
    required this.projects,
  });

  @override
  int get hashCode =>
      outputZipPath.hashCode ^ includeOriginals.hashCode ^ projects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportSelectionRequest &&
          runtimeType == other.runtimeType &&
          outputZipPath == other.outputZipPath &&
          includeOriginals == other.includeOriginals &&
          projects == other.projects;
}

/// Project-level watermark template persisted in v2 manifests so a restored
/// project keeps its original look instead of falling back to defaults.
class ExportWatermarkSettings {
  final String position;
  final double opacity;
  final int accentColorArgb;
  final double fontScale;

  const ExportWatermarkSettings({
    required this.position,
    required this.opacity,
    required this.accentColorArgb,
    required this.fontScale,
  });

  @override
  int get hashCode =>
      position.hashCode ^
      opacity.hashCode ^
      accentColorArgb.hashCode ^
      fontScale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportWatermarkSettings &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          opacity == other.opacity &&
          accentColorArgb == other.accentColorArgb &&
          fontScale == other.fontScale;
}

class ExtractArchivePhotoRequest {
  final String zipPath;
  final String photoNumber;
  final String renderedDestination;
  final String? originalDestination;

  const ExtractArchivePhotoRequest({
    required this.zipPath,
    required this.photoNumber,
    required this.renderedDestination,
    this.originalDestination,
  });

  @override
  int get hashCode =>
      zipPath.hashCode ^
      photoNumber.hashCode ^
      renderedDestination.hashCode ^
      originalDestination.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractArchivePhotoRequest &&
          runtimeType == other.runtimeType &&
          zipPath == other.zipPath &&
          photoNumber == other.photoNumber &&
          renderedDestination == other.renderedDestination &&
          originalDestination == other.originalDestination;
}

class ExtractProjectBundleEntryRequest {
  final String zipPath;
  final String archivePath;
  final String outputPath;

  const ExtractProjectBundleEntryRequest({
    required this.zipPath,
    required this.archivePath,
    required this.outputPath,
  });

  @override
  int get hashCode =>
      zipPath.hashCode ^ archivePath.hashCode ^ outputPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractProjectBundleEntryRequest &&
          runtimeType == other.runtimeType &&
          zipPath == other.zipPath &&
          archivePath == other.archivePath &&
          outputPath == other.outputPath;
}

class ExtractedArchivePhoto {
  final String renderedPath;
  final String? originalPath;

  const ExtractedArchivePhoto({required this.renderedPath, this.originalPath});

  @override
  int get hashCode => renderedPath.hashCode ^ originalPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExtractedArchivePhoto &&
          runtimeType == other.runtimeType &&
          renderedPath == other.renderedPath &&
          originalPath == other.originalPath;
}

/// Validated content of a restorable single-project backup ZIP.
class ProjectArchivePreview {
  final int schemaVersion;
  final String projectName;
  final String? projectDescription;
  final String? projectCreatedAt;
  final String? snapshotAt;
  final int omittedProcessingCount;
  final int omittedFailedCount;
  final bool isPartial;
  final bool includesOriginals;

  /// Normalized lifecycle status: always one of `active`, `completed`, `archived`.
  /// Schema 1..=4 archives are normalized to `active`.
  final String projectLifecycleStatus;

  /// Normalized pin flag. Schema 1..=4 archives are normalized to `false`.
  final bool projectIsPinned;
  final ArchiveWatermarkSettings? watermark;
  final List<ArchivePhotoPreview> photos;
  final List<ArchiveCaptureTemplate> templates;

  const ProjectArchivePreview({
    required this.schemaVersion,
    required this.projectName,
    this.projectDescription,
    this.projectCreatedAt,
    this.snapshotAt,
    required this.omittedProcessingCount,
    required this.omittedFailedCount,
    required this.isPartial,
    required this.includesOriginals,
    required this.projectLifecycleStatus,
    required this.projectIsPinned,
    this.watermark,
    required this.photos,
    required this.templates,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^
      projectName.hashCode ^
      projectDescription.hashCode ^
      projectCreatedAt.hashCode ^
      snapshotAt.hashCode ^
      omittedProcessingCount.hashCode ^
      omittedFailedCount.hashCode ^
      isPartial.hashCode ^
      includesOriginals.hashCode ^
      projectLifecycleStatus.hashCode ^
      projectIsPinned.hashCode ^
      watermark.hashCode ^
      photos.hashCode ^
      templates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectArchivePreview &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          projectName == other.projectName &&
          projectDescription == other.projectDescription &&
          projectCreatedAt == other.projectCreatedAt &&
          snapshotAt == other.snapshotAt &&
          omittedProcessingCount == other.omittedProcessingCount &&
          omittedFailedCount == other.omittedFailedCount &&
          isPartial == other.isPartial &&
          includesOriginals == other.includesOriginals &&
          projectLifecycleStatus == other.projectLifecycleStatus &&
          projectIsPinned == other.projectIsPinned &&
          watermark == other.watermark &&
          photos == other.photos &&
          templates == other.templates;
}

class ProjectBundleEntryPreview {
  final String projectId;
  final String projectName;
  final String archivePath;
  final String archiveSha256;

  const ProjectBundleEntryPreview({
    required this.projectId,
    required this.projectName,
    required this.archivePath,
    required this.archiveSha256,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectName.hashCode ^
      archivePath.hashCode ^
      archiveSha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectBundleEntryPreview &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectName == other.projectName &&
          archivePath == other.archivePath &&
          archiveSha256 == other.archiveSha256;
}

class ProjectBundlePreview {
  final int schemaVersion;
  final String createdAt;
  final List<ProjectBundleEntryPreview> projects;

  const ProjectBundlePreview({
    required this.schemaVersion,
    required this.createdAt,
    required this.projects,
  });

  @override
  int get hashCode =>
      schemaVersion.hashCode ^ createdAt.hashCode ^ projects.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectBundlePreview &&
          runtimeType == other.runtimeType &&
          schemaVersion == other.schemaVersion &&
          createdAt == other.createdAt &&
          projects == other.projects;
}

class ProjectBundleSource {
  final String projectId;
  final String projectName;
  final String archivePath;

  const ProjectBundleSource({
    required this.projectId,
    required this.projectName,
    required this.archivePath,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^ projectName.hashCode ^ archivePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectBundleSource &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectName == other.projectName &&
          archivePath == other.archivePath;
}

class RenderPhotoRequest {
  final String sourcePath;
  final String outputPath;
  final String projectName;
  final String workLocation;
  final String workContent;
  final String photographer;
  final String photoNumber;
  final String capturedAt;
  final String? address;
  final String? coordinates;
  final String? notes;
  final WatermarkPosition position;
  final double opacity;
  final int accentColorArgb;
  final double fontScale;
  final String localeCode;

  const RenderPhotoRequest({
    required this.sourcePath,
    required this.outputPath,
    required this.projectName,
    required this.workLocation,
    required this.workContent,
    required this.photographer,
    required this.photoNumber,
    required this.capturedAt,
    this.address,
    this.coordinates,
    this.notes,
    required this.position,
    required this.opacity,
    required this.accentColorArgb,
    required this.fontScale,
    required this.localeCode,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      outputPath.hashCode ^
      projectName.hashCode ^
      workLocation.hashCode ^
      workContent.hashCode ^
      photographer.hashCode ^
      photoNumber.hashCode ^
      capturedAt.hashCode ^
      address.hashCode ^
      coordinates.hashCode ^
      notes.hashCode ^
      position.hashCode ^
      opacity.hashCode ^
      accentColorArgb.hashCode ^
      fontScale.hashCode ^
      localeCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderPhotoRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          outputPath == other.outputPath &&
          projectName == other.projectName &&
          workLocation == other.workLocation &&
          workContent == other.workContent &&
          photographer == other.photographer &&
          photoNumber == other.photoNumber &&
          capturedAt == other.capturedAt &&
          address == other.address &&
          coordinates == other.coordinates &&
          notes == other.notes &&
          position == other.position &&
          opacity == other.opacity &&
          accentColorArgb == other.accentColorArgb &&
          fontScale == other.fontScale &&
          localeCode == other.localeCode;
}

class RenderPhotoResult {
  final String outputPath;
  final String outputSha256;
  final int width;
  final int height;

  const RenderPhotoResult({
    required this.outputPath,
    required this.outputSha256,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^
      outputSha256.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderPhotoResult &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          outputSha256 == other.outputSha256 &&
          width == other.width &&
          height == other.height;
}

enum WatermarkPosition { bottomLeft, bottomRight }
