// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `add_file_to_zip`, `argb_to_rgba`, `blend_rect`, `draw_watermark_card`, `non_empty`, `safe_archive_component`, `validate_render_request`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CsvRow`, `ExportManifest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<String> sha256File({required String path}) =>
    RustLib.instance.api.crateApiImageCoreSha256File(path: path);

Future<bool> verifyFile({
  required String path,
  required String expectedSha256,
}) => RustLib.instance.api.crateApiImageCoreVerifyFile(
  path: path,
  expectedSha256: expectedSha256,
);

Future<RenderPhotoResult> renderPhoto({required RenderPhotoRequest request}) =>
    RustLib.instance.api.crateApiImageCoreRenderPhoto(request: request);

Future<ExportProjectResult> exportProject({
  required ExportProjectRequest request,
}) => RustLib.instance.api.crateApiImageCoreExportProject(request: request);

class ExportPhotoRecord {
  final String photoNumber;
  final String watermarkedPath;
  final String? originalPath;
  final String originalSha256;
  final String capturedAt;
  final String workLocation;
  final String workContent;
  final String photographer;
  final String? address;
  final String? coordinates;
  final String? notes;

  const ExportPhotoRecord({
    required this.photoNumber,
    required this.watermarkedPath,
    this.originalPath,
    required this.originalSha256,
    required this.capturedAt,
    required this.workLocation,
    required this.workContent,
    required this.photographer,
    this.address,
    this.coordinates,
    this.notes,
  });

  @override
  int get hashCode =>
      photoNumber.hashCode ^
      watermarkedPath.hashCode ^
      originalPath.hashCode ^
      originalSha256.hashCode ^
      capturedAt.hashCode ^
      workLocation.hashCode ^
      workContent.hashCode ^
      photographer.hashCode ^
      address.hashCode ^
      coordinates.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportPhotoRecord &&
          runtimeType == other.runtimeType &&
          photoNumber == other.photoNumber &&
          watermarkedPath == other.watermarkedPath &&
          originalPath == other.originalPath &&
          originalSha256 == other.originalSha256 &&
          capturedAt == other.capturedAt &&
          workLocation == other.workLocation &&
          workContent == other.workContent &&
          photographer == other.photographer &&
          address == other.address &&
          coordinates == other.coordinates &&
          notes == other.notes;
}

class ExportProjectRequest {
  final String projectId;
  final String projectName;
  final String outputZipPath;
  final bool includeOriginals;
  final List<ExportPhotoRecord> photos;

  const ExportProjectRequest({
    required this.projectId,
    required this.projectName,
    required this.outputZipPath,
    required this.includeOriginals,
    required this.photos,
  });

  @override
  int get hashCode =>
      projectId.hashCode ^
      projectName.hashCode ^
      outputZipPath.hashCode ^
      includeOriginals.hashCode ^
      photos.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportProjectRequest &&
          runtimeType == other.runtimeType &&
          projectId == other.projectId &&
          projectName == other.projectName &&
          outputZipPath == other.outputZipPath &&
          includeOriginals == other.includeOriginals &&
          photos == other.photos;
}

class ExportProjectResult {
  final String outputZipPath;
  final String archiveSha256;
  final int photoCount;

  const ExportProjectResult({
    required this.outputZipPath,
    required this.archiveSha256,
    required this.photoCount,
  });

  @override
  int get hashCode =>
      outputZipPath.hashCode ^ archiveSha256.hashCode ^ photoCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ExportProjectResult &&
          runtimeType == other.runtimeType &&
          outputZipPath == other.outputZipPath &&
          archiveSha256 == other.archiveSha256 &&
          photoCount == other.photoCount;
}

class RenderPhotoRequest {
  final String sourcePath;
  final String outputPath;
  final String projectName;
  final String workLocation;
  final String workContent;
  final String photographer;
  final String photoNumber;
  final String capturedAt;
  final String? address;
  final String? coordinates;
  final String? notes;
  final WatermarkPosition position;
  final double opacity;
  final int accentColorArgb;

  const RenderPhotoRequest({
    required this.sourcePath,
    required this.outputPath,
    required this.projectName,
    required this.workLocation,
    required this.workContent,
    required this.photographer,
    required this.photoNumber,
    required this.capturedAt,
    this.address,
    this.coordinates,
    this.notes,
    required this.position,
    required this.opacity,
    required this.accentColorArgb,
  });

  @override
  int get hashCode =>
      sourcePath.hashCode ^
      outputPath.hashCode ^
      projectName.hashCode ^
      workLocation.hashCode ^
      workContent.hashCode ^
      photographer.hashCode ^
      photoNumber.hashCode ^
      capturedAt.hashCode ^
      address.hashCode ^
      coordinates.hashCode ^
      notes.hashCode ^
      position.hashCode ^
      opacity.hashCode ^
      accentColorArgb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderPhotoRequest &&
          runtimeType == other.runtimeType &&
          sourcePath == other.sourcePath &&
          outputPath == other.outputPath &&
          projectName == other.projectName &&
          workLocation == other.workLocation &&
          workContent == other.workContent &&
          photographer == other.photographer &&
          photoNumber == other.photoNumber &&
          capturedAt == other.capturedAt &&
          address == other.address &&
          coordinates == other.coordinates &&
          notes == other.notes &&
          position == other.position &&
          opacity == other.opacity &&
          accentColorArgb == other.accentColorArgb;
}

class RenderPhotoResult {
  final String outputPath;
  final String outputSha256;
  final int width;
  final int height;

  const RenderPhotoResult({
    required this.outputPath,
    required this.outputSha256,
    required this.width,
    required this.height,
  });

  @override
  int get hashCode =>
      outputPath.hashCode ^
      outputSha256.hashCode ^
      width.hashCode ^
      height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderPhotoResult &&
          runtimeType == other.runtimeType &&
          outputPath == other.outputPath &&
          outputSha256 == other.outputSha256 &&
          width == other.width &&
          height == other.height;
}

enum WatermarkPosition { bottomLeft, bottomRight }
