// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../nas.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

/// Probes the configured server: connectivity, authentication and root
/// writability. Returns protocol details (the SFTP host key fingerprint)
/// the caller should persist after the user accepts them.
Future<NasTestDetails> nasTestConnection({required NasConfig config}) =>
    RustLib.instance.api.crateApiNasNasTestConnection(config: config);

/// Uploads the local file to `{root}/{project_key}/{file_name}`, creating
/// every missing directory on the way and overwriting previous content so
/// retries converge. Reads the whole file into memory first: watermarked
/// JPEGs are single-digit megabytes and every protocol here prefers a
/// known-size body over streaming bookkeeping.
Future<void> nasUpload({required NasUploadRequest request}) =>
    RustLib.instance.api.crateApiNasNasUpload(request: request);

/// One upload job: where the file comes from and where it goes.
class NasUploadRequest {
  final NasConfig config;

  /// Sanitized project directory name below the configured root.
  final String projectKey;

  /// Remote file name, typically `{照片编号}.jpg`.
  final String fileName;

  /// Local path of the rendered watermarked JPEG.
  final String localPath;

  const NasUploadRequest({
    required this.config,
    required this.projectKey,
    required this.fileName,
    required this.localPath,
  });

  @override
  int get hashCode =>
      config.hashCode ^
      projectKey.hashCode ^
      fileName.hashCode ^
      localPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NasUploadRequest &&
          runtimeType == other.runtimeType &&
          config == other.config &&
          projectKey == other.projectKey &&
          fileName == other.fileName &&
          localPath == other.localPath;
}
