// Autogenerated from Pigeon (v27.1.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum SystemApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum CameraOutcome: Int, CaseIterable {
  case captured = 0
  case cancelled = 1
  case failed = 2
}

enum ArchiveSaveOutcome: Int, CaseIterable {
  case saved = 0
  case cancelled = 1
}

enum LocationOutcome: Int, CaseIterable {
  case precise = 0
  case approximate = 1
  case permissionDenied = 2
  case servicesDisabled = 3
  case timeout = 4
  case unavailable = 5
}

enum LocationPermissionState: Int, CaseIterable {
  case granted = 0
  case denied = 1
  case permanentlyDenied = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct CameraCaptureResult: Hashable, CustomStringConvertible {
  var outcome: CameraOutcome
  var outputPath: String
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CameraCaptureResult? {
    let outcome = pigeonVar_list[0] as! CameraOutcome
    let outputPath = pigeonVar_list[1] as! String
    let errorMessage: String? = nilOrValue(pigeonVar_list[2])

    return CameraCaptureResult(
      outcome: outcome,
      outputPath: outputPath,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      outcome,
      outputPath,
      errorMessage,
    ]
  }
  static func == (lhs: CameraCaptureResult, rhs: CameraCaptureResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SystemApiPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && SystemApiPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && SystemApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CameraCaptureResult")
    SystemApiPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "CameraCaptureResult(outcome: \(String(describing: outcome)), outputPath: \(String(describing: outputPath)), errorMessage: \(String(describing: errorMessage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct RecoveredCameraCapture: Hashable, CustomStringConvertible {
  var captureId: String
  var outputPath: String
  var hasContent: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecoveredCameraCapture? {
    let captureId = pigeonVar_list[0] as! String
    let outputPath = pigeonVar_list[1] as! String
    let hasContent = pigeonVar_list[2] as! Bool

    return RecoveredCameraCapture(
      captureId: captureId,
      outputPath: outputPath,
      hasContent: hasContent
    )
  }
  func toList() -> [Any?] {
    return [
      captureId,
      outputPath,
      hasContent,
    ]
  }
  static func == (lhs: RecoveredCameraCapture, rhs: RecoveredCameraCapture) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SystemApiPigeonInternal.deepEquals(lhs.captureId, rhs.captureId) && SystemApiPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && SystemApiPigeonInternal.deepEquals(lhs.hasContent, rhs.hasContent)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecoveredCameraCapture")
    SystemApiPigeonInternal.deepHash(value: captureId, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: hasContent, hasher: &hasher)
  }

  public var description: String {
    return "RecoveredCameraCapture(captureId: \(String(describing: captureId)), outputPath: \(String(describing: outputPath)), hasContent: \(String(describing: hasContent)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct LocationResult: Hashable, CustomStringConvertible {
  var outcome: LocationOutcome
  var latitude: Double? = nil
  var longitude: Double? = nil
  var accuracyMeters: Double? = nil
  var address: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LocationResult? {
    let outcome = pigeonVar_list[0] as! LocationOutcome
    let latitude: Double? = nilOrValue(pigeonVar_list[1])
    let longitude: Double? = nilOrValue(pigeonVar_list[2])
    let accuracyMeters: Double? = nilOrValue(pigeonVar_list[3])
    let address: String? = nilOrValue(pigeonVar_list[4])
    let errorMessage: String? = nilOrValue(pigeonVar_list[5])

    return LocationResult(
      outcome: outcome,
      latitude: latitude,
      longitude: longitude,
      accuracyMeters: accuracyMeters,
      address: address,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      outcome,
      latitude,
      longitude,
      accuracyMeters,
      address,
      errorMessage,
    ]
  }
  static func == (lhs: LocationResult, rhs: LocationResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SystemApiPigeonInternal.deepEquals(lhs.outcome, rhs.outcome) && SystemApiPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && SystemApiPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && SystemApiPigeonInternal.deepEquals(lhs.accuracyMeters, rhs.accuracyMeters) && SystemApiPigeonInternal.deepEquals(lhs.address, rhs.address) && SystemApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("LocationResult")
    SystemApiPigeonInternal.deepHash(value: outcome, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: longitude, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: accuracyMeters, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: address, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "LocationResult(outcome: \(String(describing: outcome)), latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)), accuracyMeters: \(String(describing: accuracyMeters)), address: \(String(describing: address)), errorMessage: \(String(describing: errorMessage)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageMetadataResult: Hashable, CustomStringConvertible {
  var width: Int64
  var height: Int64
  var fileSizeBytes: Int64
  var mimeType: String
  var latitude: Double? = nil
  var longitude: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageMetadataResult? {
    let width = pigeonVar_list[0] as! Int64
    let height = pigeonVar_list[1] as! Int64
    let fileSizeBytes = pigeonVar_list[2] as! Int64
    let mimeType = pigeonVar_list[3] as! String
    let latitude: Double? = nilOrValue(pigeonVar_list[4])
    let longitude: Double? = nilOrValue(pigeonVar_list[5])

    return ImageMetadataResult(
      width: width,
      height: height,
      fileSizeBytes: fileSizeBytes,
      mimeType: mimeType,
      latitude: latitude,
      longitude: longitude
    )
  }
  func toList() -> [Any?] {
    return [
      width,
      height,
      fileSizeBytes,
      mimeType,
      latitude,
      longitude,
    ]
  }
  static func == (lhs: ImageMetadataResult, rhs: ImageMetadataResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SystemApiPigeonInternal.deepEquals(lhs.width, rhs.width) && SystemApiPigeonInternal.deepEquals(lhs.height, rhs.height) && SystemApiPigeonInternal.deepEquals(lhs.fileSizeBytes, rhs.fileSizeBytes) && SystemApiPigeonInternal.deepEquals(lhs.mimeType, rhs.mimeType) && SystemApiPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && SystemApiPigeonInternal.deepEquals(lhs.longitude, rhs.longitude)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageMetadataResult")
    SystemApiPigeonInternal.deepHash(value: width, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: height, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: fileSizeBytes, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: mimeType, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: latitude, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: longitude, hasher: &hasher)
  }

  public var description: String {
    return "ImageMetadataResult(width: \(String(describing: width)), height: \(String(describing: height)), fileSizeBytes: \(String(describing: fileSizeBytes)), mimeType: \(String(describing: mimeType)), latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaPublishResult: Hashable, CustomStringConvertible {
  var contentUri: String
  /// Every prior MediaStore URI explicitly owned by this stable capture and
  /// superseded by the new content, including leftovers folded from an
  /// interrupted publish journal. Native code does not delete these rows;
  /// the caller must durably queue reference-checked, delete-only cleanup and
  /// must never re-publish or report failure because this list is non-empty.
  var supersededUris: [String]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaPublishResult? {
    let contentUri = pigeonVar_list[0] as! String
    let supersededUris: [String]? = nilOrValue(pigeonVar_list[1])

    return MediaPublishResult(
      contentUri: contentUri,
      supersededUris: supersededUris
    )
  }
  func toList() -> [Any?] {
    return [
      contentUri,
      supersededUris,
    ]
  }
  static func == (lhs: MediaPublishResult, rhs: MediaPublishResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SystemApiPigeonInternal.deepEquals(lhs.contentUri, rhs.contentUri) && SystemApiPigeonInternal.deepEquals(lhs.supersededUris, rhs.supersededUris)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaPublishResult")
    SystemApiPigeonInternal.deepHash(value: contentUri, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: supersededUris, hasher: &hasher)
  }

  public var description: String {
    return "MediaPublishResult(contentUri: \(String(describing: contentUri)), supersededUris: \(String(describing: supersededUris)))"
  }
}

/// A natively persisted publish intent that survived a process death before
/// the caller committed the new URI to its database.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RecoveredPublishJournal: Hashable, CustomStringConvertible {
  /// The stable capture identity the publish was keyed by. Callers
  /// reconcile their database row by this ID — NEVER by photo number,
  /// which a backup restore can duplicate across projects.
  var captureId: String
  /// The finalized new MediaStore URI. It is already visible in the gallery.
  var contentUri: String
  /// Every superseded candidate URI the publisher intended to delete. Some
  /// may already be gone — deletes are idempotent, so re-queuing them is
  /// safe and converges.
  var supersededUris: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RecoveredPublishJournal? {
    let captureId = pigeonVar_list[0] as! String
    let contentUri = pigeonVar_list[1] as! String
    let supersededUris = pigeonVar_list[2] as! [String]

    return RecoveredPublishJournal(
      captureId: captureId,
      contentUri: contentUri,
      supersededUris: supersededUris
    )
  }
  func toList() -> [Any?] {
    return [
      captureId,
      contentUri,
      supersededUris,
    ]
  }
  static func == (lhs: RecoveredPublishJournal, rhs: RecoveredPublishJournal) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return SystemApiPigeonInternal.deepEquals(lhs.captureId, rhs.captureId) && SystemApiPigeonInternal.deepEquals(lhs.contentUri, rhs.contentUri) && SystemApiPigeonInternal.deepEquals(lhs.supersededUris, rhs.supersededUris)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("RecoveredPublishJournal")
    SystemApiPigeonInternal.deepHash(value: captureId, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: contentUri, hasher: &hasher)
    SystemApiPigeonInternal.deepHash(value: supersededUris, hasher: &hasher)
  }

  public var description: String {
    return "RecoveredPublishJournal(captureId: \(String(describing: captureId)), contentUri: \(String(describing: contentUri)), supersededUris: \(String(describing: supersededUris)))"
  }
}

private class SystemApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CameraOutcome(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ArchiveSaveOutcome(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LocationOutcome(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LocationPermissionState(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return CameraCaptureResult.fromList(self.readValue() as! [Any?])
    case 134:
      return RecoveredCameraCapture.fromList(self.readValue() as! [Any?])
    case 135:
      return LocationResult.fromList(self.readValue() as! [Any?])
    case 136:
      return ImageMetadataResult.fromList(self.readValue() as! [Any?])
    case 137:
      return MediaPublishResult.fromList(self.readValue() as! [Any?])
    case 138:
      return RecoveredPublishJournal.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class SystemApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CameraOutcome {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ArchiveSaveOutcome {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocationOutcome {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? LocationPermissionState {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? CameraCaptureResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? RecoveredCameraCapture {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? LocationResult {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? ImageMetadataResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? MediaPublishResult {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? RecoveredPublishJournal {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class SystemApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return SystemApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return SystemApiPigeonCodecWriter(data: data)
  }
}

class SystemApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = SystemApiPigeonCodec(readerWriter: SystemApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol SiteMarkSystemApi {
  func createCameraTarget(captureId: String) throws -> String
  func launchCamera(captureId: String, completion: @escaping (Result<CameraCaptureResult, Error>) -> Void)
  func recoverCameraCapture() throws -> RecoveredCameraCapture?
  func finishCameraCapture(captureId: String, keepOriginal: Bool) throws
  func getLocationPermissionState() throws -> LocationPermissionState
  func requestLocationPermission(completion: @escaping (Result<LocationPermissionState, Error>) -> Void)
  func openApplicationSettings() throws
  func inspectImage(path: String, completion: @escaping (Result<ImageMetadataResult, Error>) -> Void)
  func requestCurrentLocation(timeoutMillis: Int64, completion: @escaping (Result<LocationResult, Error>) -> Void)
  /// Publishes [sourcePath] into the system gallery under [displayName].
  ///
  /// [captureId] is the caller's stable identity for the capture: it keys
  /// the durable publish journal and disambiguates records that share a
  /// photo number after a backup restore. [publishedUri] is the exact
  /// previously published URI this publish replaces — the native side
  /// reports ONLY that URI (plus any leftover journaled URI of the same
  /// capture) as a pending cleanup candidate; it never deletes gallery
  /// rows itself, because a legacy upgrade can leave TWO records sharing
  /// one URI and only the caller can check cross-record references.
  func publishJpeg(sourcePath: String, displayName: String, captureId: String, publishedUri: String?, completion: @escaping (Result<MediaPublishResult, Error>) -> Void)
  func recoverPublishJournals() throws -> [RecoveredPublishJournal]?
  /// Clears the capture's publish journal ONLY when it still records
  /// [expectedContentUri]. An older operation whose newer same-capture
  /// publish already overwrote the journal must NOT clear the newer
  /// entry, or the newer publish would become unrecoverable.
  func clearPublishJournal(captureId: String, expectedContentUri: String) throws
  func saveArchive(sourcePath: String, suggestedName: String, completion: @escaping (Result<ArchiveSaveOutcome, Error>) -> Void)
  func deletePublishedImage(contentUri: String, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class SiteMarkSystemApiSetup {
  static var codec: FlutterStandardMessageCodec { SystemApiPigeonCodec.shared }
  /// Sets up an instance of `SiteMarkSystemApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: SiteMarkSystemApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let createCameraTargetChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.createCameraTarget\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createCameraTargetChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureIdArg = args[0] as! String
        do {
          let result = try api.createCameraTarget(captureId: captureIdArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createCameraTargetChannel.setMessageHandler(nil)
    }
    let launchCameraChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.launchCamera\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      launchCameraChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureIdArg = args[0] as! String
        api.launchCamera(captureId: captureIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      launchCameraChannel.setMessageHandler(nil)
    }
    let recoverCameraCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.recoverCameraCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recoverCameraCaptureChannel.setMessageHandler { _, reply in
        do {
          let result = try api.recoverCameraCapture()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      recoverCameraCaptureChannel.setMessageHandler(nil)
    }
    let finishCameraCaptureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.finishCameraCapture\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      finishCameraCaptureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureIdArg = args[0] as! String
        let keepOriginalArg = args[1] as! Bool
        do {
          try api.finishCameraCapture(captureId: captureIdArg, keepOriginal: keepOriginalArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      finishCameraCaptureChannel.setMessageHandler(nil)
    }
    let getLocationPermissionStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.getLocationPermissionState\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLocationPermissionStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLocationPermissionState()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLocationPermissionStateChannel.setMessageHandler(nil)
    }
    let requestLocationPermissionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.requestLocationPermission\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestLocationPermissionChannel.setMessageHandler { _, reply in
        api.requestLocationPermission { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestLocationPermissionChannel.setMessageHandler(nil)
    }
    let openApplicationSettingsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.openApplicationSettings\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openApplicationSettingsChannel.setMessageHandler { _, reply in
        do {
          try api.openApplicationSettings()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      openApplicationSettingsChannel.setMessageHandler(nil)
    }
    let inspectImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.inspectImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      inspectImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.inspectImage(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      inspectImageChannel.setMessageHandler(nil)
    }
    let requestCurrentLocationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.requestCurrentLocation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestCurrentLocationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let timeoutMillisArg = args[0] as! Int64
        api.requestCurrentLocation(timeoutMillis: timeoutMillisArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestCurrentLocationChannel.setMessageHandler(nil)
    }
    /// Publishes [sourcePath] into the system gallery under [displayName].
    ///
    /// [captureId] is the caller's stable identity for the capture: it keys
    /// the durable publish journal and disambiguates records that share a
    /// photo number after a backup restore. [publishedUri] is the exact
    /// previously published URI this publish replaces — the native side
    /// reports ONLY that URI (plus any leftover journaled URI of the same
    /// capture) as a pending cleanup candidate; it never deletes gallery
    /// rows itself, because a legacy upgrade can leave TWO records sharing
    /// one URI and only the caller can check cross-record references.
    let publishJpegChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.publishJpeg\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      publishJpegChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourcePathArg = args[0] as! String
        let displayNameArg = args[1] as! String
        let captureIdArg = args[2] as! String
        let publishedUriArg: String? = nilOrValue(args[3])
        api.publishJpeg(sourcePath: sourcePathArg, displayName: displayNameArg, captureId: captureIdArg, publishedUri: publishedUriArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      publishJpegChannel.setMessageHandler(nil)
    }
    let recoverPublishJournalsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.recoverPublishJournals\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      recoverPublishJournalsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.recoverPublishJournals()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      recoverPublishJournalsChannel.setMessageHandler(nil)
    }
    /// Clears the capture's publish journal ONLY when it still records
    /// [expectedContentUri]. An older operation whose newer same-capture
    /// publish already overwrote the journal must NOT clear the newer
    /// entry, or the newer publish would become unrecoverable.
    let clearPublishJournalChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.clearPublishJournal\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearPublishJournalChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let captureIdArg = args[0] as! String
        let expectedContentUriArg = args[1] as! String
        do {
          try api.clearPublishJournal(captureId: captureIdArg, expectedContentUri: expectedContentUriArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearPublishJournalChannel.setMessageHandler(nil)
    }
    let saveArchiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.saveArchive\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      saveArchiveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sourcePathArg = args[0] as! String
        let suggestedNameArg = args[1] as! String
        api.saveArchive(sourcePath: sourcePathArg, suggestedName: suggestedNameArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      saveArchiveChannel.setMessageHandler(nil)
    }
    let deletePublishedImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.sitemark_system_api.SiteMarkSystemApi.deletePublishedImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deletePublishedImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let contentUriArg = args[0] as! String
        api.deletePublishedImage(contentUri: contentUriArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deletePublishedImageChannel.setMessageHandler(nil)
    }
  }
}
